/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const ACCEPT_OWNERSHIP_DISCRIMINATOR = new Uint8Array([172, 23, 43, 13, 238, 213, 85, 150])

export function getAcceptOwnershipDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(ACCEPT_OWNERSHIP_DISCRIMINATOR)
}

export type AcceptOwnershipInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountPendingMaster extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMasterAccount extends string
				? WritableAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountPendingMaster extends string
				? WritableSignerAccount<TAccountPendingMaster> & AccountSignerMeta<TAccountPendingMaster>
				: TAccountPendingMaster,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type AcceptOwnershipInstructionData = {
	discriminator: ReadonlyUint8Array
}

export type AcceptOwnershipInstructionDataArgs = {}

export function getAcceptOwnershipInstructionDataEncoder(): FixedSizeEncoder<AcceptOwnershipInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
		value => ({ ...value, discriminator: ACCEPT_OWNERSHIP_DISCRIMINATOR })
	)
}

export function getAcceptOwnershipInstructionDataDecoder(): FixedSizeDecoder<AcceptOwnershipInstructionData> {
	return getStructDecoder([["discriminator", fixDecoderSize(getBytesDecoder(), 8)]])
}

export function getAcceptOwnershipInstructionDataCodec(): FixedSizeCodec<
	AcceptOwnershipInstructionDataArgs,
	AcceptOwnershipInstructionData
> {
	return combineCodec(
		getAcceptOwnershipInstructionDataEncoder(),
		getAcceptOwnershipInstructionDataDecoder()
	)
}

export type AcceptOwnershipAsyncInput<
	TAccountMasterAccount extends string = string,
	TAccountPendingMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	masterAccount?: Address<TAccountMasterAccount>
	pendingMaster: TransactionSigner<TAccountPendingMaster>
	systemProgram?: Address<TAccountSystemProgram>
}

export async function getAcceptOwnershipInstructionAsync<
	TAccountMasterAccount extends string,
	TAccountPendingMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: AcceptOwnershipAsyncInput<
		TAccountMasterAccount,
		TAccountPendingMaster,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	AcceptOwnershipInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountPendingMaster,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		masterAccount: { value: input.masterAccount ?? null, isWritable: true },
		pendingMaster: { value: input.pendingMaster ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Resolve default values.
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.pendingMaster),
			getAccountMeta(accounts.systemProgram)
		],
		data: getAcceptOwnershipInstructionDataEncoder().encode({}),
		programAddress
	} as AcceptOwnershipInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountPendingMaster,
		TAccountSystemProgram
	>)
}

export type AcceptOwnershipInput<
	TAccountMasterAccount extends string = string,
	TAccountPendingMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	masterAccount: Address<TAccountMasterAccount>
	pendingMaster: TransactionSigner<TAccountPendingMaster>
	systemProgram?: Address<TAccountSystemProgram>
}

export function getAcceptOwnershipInstruction<
	TAccountMasterAccount extends string,
	TAccountPendingMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: AcceptOwnershipInput<TAccountMasterAccount, TAccountPendingMaster, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): AcceptOwnershipInstruction<
	TProgramAddress,
	TAccountMasterAccount,
	TAccountPendingMaster,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		masterAccount: { value: input.masterAccount ?? null, isWritable: true },
		pendingMaster: { value: input.pendingMaster ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.pendingMaster),
			getAccountMeta(accounts.systemProgram)
		],
		data: getAcceptOwnershipInstructionDataEncoder().encode({}),
		programAddress
	} as AcceptOwnershipInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountPendingMaster,
		TAccountSystemProgram
	>)
}

export type ParsedAcceptOwnershipInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		masterAccount: TAccountMetas[0]
		pendingMaster: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: AcceptOwnershipInstructionData
}

export function parseAcceptOwnershipInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedAcceptOwnershipInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			masterAccount: getNextAccount(),
			pendingMaster: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getAcceptOwnershipInstructionDataDecoder().decode(instruction.data)
	}
}
