/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const INITIALIZE_VAULT_DISCRIMINATOR = new Uint8Array([48, 191, 163, 44, 71, 129, 63, 164])

export function getInitializeVaultDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(INITIALIZE_VAULT_DISCRIMINATOR)
}

export type InitializeVaultInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountPool extends string | AccountMeta<string> = string,
	TAccountPoolTokenAccount extends string | AccountMeta<string> = string,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountMaster extends string | AccountMeta<string> = string,
	TAccountMint extends string | AccountMeta<string> = string,
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPool extends string ? WritableAccount<TAccountPool> : TAccountPool,
			TAccountPoolTokenAccount extends string
				? WritableAccount<TAccountPoolTokenAccount>
				: TAccountPoolTokenAccount,
			TAccountMasterAccount extends string
				? ReadonlyAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountMaster extends string
				? WritableSignerAccount<TAccountMaster> & AccountSignerMeta<TAccountMaster>
				: TAccountMaster,
			TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type InitializeVaultInstructionData = {
	discriminator: ReadonlyUint8Array
}

export type InitializeVaultInstructionDataArgs = {}

export function getInitializeVaultInstructionDataEncoder(): FixedSizeEncoder<InitializeVaultInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
		value => ({ ...value, discriminator: INITIALIZE_VAULT_DISCRIMINATOR })
	)
}

export function getInitializeVaultInstructionDataDecoder(): FixedSizeDecoder<InitializeVaultInstructionData> {
	return getStructDecoder([["discriminator", fixDecoderSize(getBytesDecoder(), 8)]])
}

export function getInitializeVaultInstructionDataCodec(): FixedSizeCodec<
	InitializeVaultInstructionDataArgs,
	InitializeVaultInstructionData
> {
	return combineCodec(
		getInitializeVaultInstructionDataEncoder(),
		getInitializeVaultInstructionDataDecoder()
	)
}

export type InitializeVaultAsyncInput<
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountMint extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	pool?: Address<TAccountPool>
	poolTokenAccount?: Address<TAccountPoolTokenAccount>
	masterAccount?: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	mint: Address<TAccountMint>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
}

export async function getInitializeVaultInstructionAsync<
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountMint extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: InitializeVaultAsyncInput<
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountMint,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	InitializeVaultInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountMint,
		TAccountTokenProgram,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Resolve default values.
	if (!accounts.pool.value) {
		accounts.pool.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.poolTokenAccount.value) {
		accounts.poolTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.pool.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitializeVaultInstructionDataEncoder().encode({}),
		programAddress
	} as InitializeVaultInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountMint,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type InitializeVaultInput<
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountMint extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	pool: Address<TAccountPool>
	poolTokenAccount: Address<TAccountPoolTokenAccount>
	masterAccount: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	mint: Address<TAccountMint>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
}

export function getInitializeVaultInstruction<
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountMint extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: InitializeVaultInput<
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountMint,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): InitializeVaultInstruction<
	TProgramAddress,
	TAccountPool,
	TAccountPoolTokenAccount,
	TAccountMasterAccount,
	TAccountMaster,
	TAccountMint,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitializeVaultInstructionDataEncoder().encode({}),
		programAddress
	} as InitializeVaultInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountMint,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedInitializeVaultInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		pool: TAccountMetas[0]
		poolTokenAccount: TAccountMetas[1]
		masterAccount: TAccountMetas[2]
		master: TAccountMetas[3]
		mint: TAccountMetas[4]
		tokenProgram: TAccountMetas[5]
		systemProgram: TAccountMetas[6]
	}
	data: InitializeVaultInstructionData
}

export function parseInitializeVaultInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeVaultInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 7) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			pool: getNextAccount(),
			poolTokenAccount: getNextAccount(),
			masterAccount: getNextAccount(),
			master: getNextAccount(),
			mint: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getInitializeVaultInstructionDataDecoder().decode(instruction.data)
	}
}
