/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressDecoder,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getF64Decoder,
	getF64Encoder,
	getI32Decoder,
	getI32Encoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	getU16Decoder,
	getU16Encoder,
	getU32Decoder,
	getU32Encoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectSome, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const INITIALIZE_MARKET_DISCRIMINATOR = new Uint8Array([35, 35, 189, 193, 155, 48, 170, 203])

export function getInitializeMarketDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(INITIALIZE_MARKET_DISCRIMINATOR)
}

export type InitializeMarketInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountMaster extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? WritableAccount<TAccountMarket> : TAccountMarket,
			TAccountMasterAccount extends string
				? ReadonlyAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountMaster extends string
				? WritableSignerAccount<TAccountMaster> & AccountSignerMeta<TAccountMaster>
				: TAccountMaster,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type InitializeMarketInstructionData = {
	discriminator: ReadonlyUint8Array
	feedId: ReadonlyUint8Array
	minSettleDelayEpochsSecs: number
	maxSettleDelayEpochsSecs: number
	feeBps: number
	callLambda: number
	putLambda: number
	vegaBuffer: number
	halfLifeSecs: bigint
	stalenessMaxSec: number
	minStake: bigint
	maxStake: bigint
	initialIv: number
	backAuthority: Address
	priceExponent: number
	minPremiumBps: number
	minSigma2: number
	maxSigma2: number
}

export type InitializeMarketInstructionDataArgs = {
	feedId: ReadonlyUint8Array
	minSettleDelayEpochsSecs: number
	maxSettleDelayEpochsSecs: number
	feeBps: number
	callLambda: number
	putLambda: number
	vegaBuffer: number
	halfLifeSecs: number | bigint
	stalenessMaxSec: number
	minStake: number | bigint
	maxStake: number | bigint
	initialIv: number
	backAuthority: Address
	priceExponent: number
	minPremiumBps: number
	minSigma2: number
	maxSigma2: number
}

export function getInitializeMarketInstructionDataEncoder(): FixedSizeEncoder<InitializeMarketInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["feedId", fixEncoderSize(getBytesEncoder(), 32)],
			["minSettleDelayEpochsSecs", getU32Encoder()],
			["maxSettleDelayEpochsSecs", getU32Encoder()],
			["feeBps", getU16Encoder()],
			["callLambda", getF64Encoder()],
			["putLambda", getF64Encoder()],
			["vegaBuffer", getF64Encoder()],
			["halfLifeSecs", getU64Encoder()],
			["stalenessMaxSec", getU32Encoder()],
			["minStake", getU64Encoder()],
			["maxStake", getU64Encoder()],
			["initialIv", getF64Encoder()],
			["backAuthority", getAddressEncoder()],
			["priceExponent", getI32Encoder()],
			["minPremiumBps", getU16Encoder()],
			["minSigma2", getF64Encoder()],
			["maxSigma2", getF64Encoder()]
		]),
		value => ({ ...value, discriminator: INITIALIZE_MARKET_DISCRIMINATOR })
	)
}

export function getInitializeMarketInstructionDataDecoder(): FixedSizeDecoder<InitializeMarketInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["feedId", fixDecoderSize(getBytesDecoder(), 32)],
		["minSettleDelayEpochsSecs", getU32Decoder()],
		["maxSettleDelayEpochsSecs", getU32Decoder()],
		["feeBps", getU16Decoder()],
		["callLambda", getF64Decoder()],
		["putLambda", getF64Decoder()],
		["vegaBuffer", getF64Decoder()],
		["halfLifeSecs", getU64Decoder()],
		["stalenessMaxSec", getU32Decoder()],
		["minStake", getU64Decoder()],
		["maxStake", getU64Decoder()],
		["initialIv", getF64Decoder()],
		["backAuthority", getAddressDecoder()],
		["priceExponent", getI32Decoder()],
		["minPremiumBps", getU16Decoder()],
		["minSigma2", getF64Decoder()],
		["maxSigma2", getF64Decoder()]
	])
}

export function getInitializeMarketInstructionDataCodec(): FixedSizeCodec<
	InitializeMarketInstructionDataArgs,
	InitializeMarketInstructionData
> {
	return combineCodec(
		getInitializeMarketInstructionDataEncoder(),
		getInitializeMarketInstructionDataDecoder()
	)
}

export type InitializeMarketAsyncInput<
	TAccountMarket extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market?: Address<TAccountMarket>
	masterAccount?: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	feedId: InitializeMarketInstructionDataArgs["feedId"]
	minSettleDelayEpochsSecs: InitializeMarketInstructionDataArgs["minSettleDelayEpochsSecs"]
	maxSettleDelayEpochsSecs: InitializeMarketInstructionDataArgs["maxSettleDelayEpochsSecs"]
	feeBps: InitializeMarketInstructionDataArgs["feeBps"]
	callLambda: InitializeMarketInstructionDataArgs["callLambda"]
	putLambda: InitializeMarketInstructionDataArgs["putLambda"]
	vegaBuffer: InitializeMarketInstructionDataArgs["vegaBuffer"]
	halfLifeSecs: InitializeMarketInstructionDataArgs["halfLifeSecs"]
	stalenessMaxSec: InitializeMarketInstructionDataArgs["stalenessMaxSec"]
	minStake: InitializeMarketInstructionDataArgs["minStake"]
	maxStake: InitializeMarketInstructionDataArgs["maxStake"]
	initialIv: InitializeMarketInstructionDataArgs["initialIv"]
	backAuthority: InitializeMarketInstructionDataArgs["backAuthority"]
	priceExponent: InitializeMarketInstructionDataArgs["priceExponent"]
	minPremiumBps: InitializeMarketInstructionDataArgs["minPremiumBps"]
	minSigma2: InitializeMarketInstructionDataArgs["minSigma2"]
	maxSigma2: InitializeMarketInstructionDataArgs["maxSigma2"]
}

export async function getInitializeMarketInstructionAsync<
	TAccountMarket extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: InitializeMarketAsyncInput<
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	InitializeMarketInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.market.value) {
		accounts.market.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 114, 107,
						101, 116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.feedId))
			]
		})
	}
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitializeMarketInstructionDataEncoder().encode(
			args as InitializeMarketInstructionDataArgs
		),
		programAddress
	} as InitializeMarketInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type InitializeMarketInput<
	TAccountMarket extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market: Address<TAccountMarket>
	masterAccount: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	feedId: InitializeMarketInstructionDataArgs["feedId"]
	minSettleDelayEpochsSecs: InitializeMarketInstructionDataArgs["minSettleDelayEpochsSecs"]
	maxSettleDelayEpochsSecs: InitializeMarketInstructionDataArgs["maxSettleDelayEpochsSecs"]
	feeBps: InitializeMarketInstructionDataArgs["feeBps"]
	callLambda: InitializeMarketInstructionDataArgs["callLambda"]
	putLambda: InitializeMarketInstructionDataArgs["putLambda"]
	vegaBuffer: InitializeMarketInstructionDataArgs["vegaBuffer"]
	halfLifeSecs: InitializeMarketInstructionDataArgs["halfLifeSecs"]
	stalenessMaxSec: InitializeMarketInstructionDataArgs["stalenessMaxSec"]
	minStake: InitializeMarketInstructionDataArgs["minStake"]
	maxStake: InitializeMarketInstructionDataArgs["maxStake"]
	initialIv: InitializeMarketInstructionDataArgs["initialIv"]
	backAuthority: InitializeMarketInstructionDataArgs["backAuthority"]
	priceExponent: InitializeMarketInstructionDataArgs["priceExponent"]
	minPremiumBps: InitializeMarketInstructionDataArgs["minPremiumBps"]
	minSigma2: InitializeMarketInstructionDataArgs["minSigma2"]
	maxSigma2: InitializeMarketInstructionDataArgs["maxSigma2"]
}

export function getInitializeMarketInstruction<
	TAccountMarket extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: InitializeMarketInput<
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): InitializeMarketInstruction<
	TProgramAddress,
	TAccountMarket,
	TAccountMasterAccount,
	TAccountMaster,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitializeMarketInstructionDataEncoder().encode(
			args as InitializeMarketInstructionDataArgs
		),
		programAddress
	} as InitializeMarketInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type ParsedInitializeMarketInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		market: TAccountMetas[0]
		masterAccount: TAccountMetas[1]
		master: TAccountMetas[2]
		systemProgram: TAccountMetas[3]
	}
	data: InitializeMarketInstructionData
}

export function parseInitializeMarketInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeMarketInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			masterAccount: getNextAccount(),
			master: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getInitializeMarketInstructionDataDecoder().decode(instruction.data)
	}
}
