/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const INITIALIZE_DISCRIMINATOR = new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237])

export function getInitializeDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(INITIALIZE_DISCRIMINATOR)
}

export type InitializeInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountPayer extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMasterAccount extends string
				? WritableAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountPayer extends string
				? WritableSignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer>
				: TAccountPayer,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type InitializeInstructionData = { discriminator: ReadonlyUint8Array }

export type InitializeInstructionDataArgs = {}

export function getInitializeInstructionDataEncoder(): FixedSizeEncoder<InitializeInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
		value => ({ ...value, discriminator: INITIALIZE_DISCRIMINATOR })
	)
}

export function getInitializeInstructionDataDecoder(): FixedSizeDecoder<InitializeInstructionData> {
	return getStructDecoder([["discriminator", fixDecoderSize(getBytesDecoder(), 8)]])
}

export function getInitializeInstructionDataCodec(): FixedSizeCodec<
	InitializeInstructionDataArgs,
	InitializeInstructionData
> {
	return combineCodec(getInitializeInstructionDataEncoder(), getInitializeInstructionDataDecoder())
}

export type InitializeAsyncInput<
	TAccountMasterAccount extends string = string,
	TAccountPayer extends string = string,
	TAccountSystemProgram extends string = string
> = {
	masterAccount?: Address<TAccountMasterAccount>
	payer: TransactionSigner<TAccountPayer>
	systemProgram?: Address<TAccountSystemProgram>
}

export async function getInitializeInstructionAsync<
	TAccountMasterAccount extends string,
	TAccountPayer extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: InitializeAsyncInput<TAccountMasterAccount, TAccountPayer, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	InitializeInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountPayer,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		masterAccount: { value: input.masterAccount ?? null, isWritable: true },
		payer: { value: input.payer ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Resolve default values.
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.payer),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitializeInstructionDataEncoder().encode({}),
		programAddress
	} as InitializeInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountPayer,
		TAccountSystemProgram
	>)
}

export type InitializeInput<
	TAccountMasterAccount extends string = string,
	TAccountPayer extends string = string,
	TAccountSystemProgram extends string = string
> = {
	masterAccount: Address<TAccountMasterAccount>
	payer: TransactionSigner<TAccountPayer>
	systemProgram?: Address<TAccountSystemProgram>
}

export function getInitializeInstruction<
	TAccountMasterAccount extends string,
	TAccountPayer extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: InitializeInput<TAccountMasterAccount, TAccountPayer, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): InitializeInstruction<
	TProgramAddress,
	TAccountMasterAccount,
	TAccountPayer,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		masterAccount: { value: input.masterAccount ?? null, isWritable: true },
		payer: { value: input.payer ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.payer),
			getAccountMeta(accounts.systemProgram)
		],
		data: getInitializeInstructionDataEncoder().encode({}),
		programAddress
	} as InitializeInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountPayer,
		TAccountSystemProgram
	>)
}

export type ParsedInitializeInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		masterAccount: TAccountMetas[0]
		payer: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: InitializeInstructionData
}

export function parseInitializeInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			masterAccount: getNextAccount(),
			payer: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getInitializeInstructionDataDecoder().decode(instruction.data)
	}
}
