/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getI64Decoder,
	getI64Encoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	getU32Decoder,
	getU32Encoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, expectSome, getAccountMetaFactory, type ResolvedAccount } from "../shared"
import {
	getPositionModeDecoder,
	getPositionModeEncoder,
	getSideDecoder,
	getSideEncoder,
	type PositionMode,
	type PositionModeArgs,
	type Side,
	type SideArgs
} from "../types"

export const OPEN_POSITION_DISCRIMINATOR = new Uint8Array([135, 128, 47, 77, 15, 152, 240, 49])

export function getOpenPositionDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(OPEN_POSITION_DISCRIMINATOR)
}

export type OpenPositionInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountPosition extends string | AccountMeta<string> = string,
	TAccountMint extends string | AccountMeta<string> = string,
	TAccountUserTokenAccount extends string | AccountMeta<string> = string,
	TAccountVault extends string | AccountMeta<string> = string,
	TAccountPool extends string | AccountMeta<string> = string,
	TAccountVaultTokenAccount extends string | AccountMeta<string> = string,
	TAccountUser extends string | AccountMeta<string> = string,
	TAccountPayer extends string | AccountMeta<string> = string,
	TAccountBackAuthority extends string | AccountMeta<string> = string,
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? WritableAccount<TAccountMarket> : TAccountMarket,
			TAccountPosition extends string ? WritableAccount<TAccountPosition> : TAccountPosition,
			TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint,
			TAccountUserTokenAccount extends string
				? WritableAccount<TAccountUserTokenAccount>
				: TAccountUserTokenAccount,
			TAccountVault extends string ? WritableAccount<TAccountVault> : TAccountVault,
			TAccountPool extends string ? WritableAccount<TAccountPool> : TAccountPool,
			TAccountVaultTokenAccount extends string
				? WritableAccount<TAccountVaultTokenAccount>
				: TAccountVaultTokenAccount,
			TAccountUser extends string
				? ReadonlySignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
				: TAccountUser,
			TAccountPayer extends string
				? WritableSignerAccount<TAccountPayer> & AccountSignerMeta<TAccountPayer>
				: TAccountPayer,
			TAccountBackAuthority extends string
				? ReadonlySignerAccount<TAccountBackAuthority> & AccountSignerMeta<TAccountBackAuthority>
				: TAccountBackAuthority,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type OpenPositionInstructionData = {
	discriminator: ReadonlyUint8Array
	id: ReadonlyUint8Array
	side: Side
	premiumAmount: bigint
	positionId: ReadonlyUint8Array
	settleDelayEpochsSecs: number
	boundaryPrice: bigint
	price: bigint
	pricePublishTime: bigint
	mode: PositionMode
}

export type OpenPositionInstructionDataArgs = {
	id: ReadonlyUint8Array
	side: SideArgs
	premiumAmount: number | bigint
	positionId: ReadonlyUint8Array
	settleDelayEpochsSecs: number
	boundaryPrice: number | bigint
	price: number | bigint
	pricePublishTime: number | bigint
	mode: PositionModeArgs
}

export function getOpenPositionInstructionDataEncoder(): FixedSizeEncoder<OpenPositionInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["id", fixEncoderSize(getBytesEncoder(), 32)],
			["side", getSideEncoder()],
			["premiumAmount", getU64Encoder()],
			["positionId", fixEncoderSize(getBytesEncoder(), 32)],
			["settleDelayEpochsSecs", getU32Encoder()],
			["boundaryPrice", getI64Encoder()],
			["price", getI64Encoder()],
			["pricePublishTime", getI64Encoder()],
			["mode", getPositionModeEncoder()]
		]),
		value => ({ ...value, discriminator: OPEN_POSITION_DISCRIMINATOR })
	)
}

export function getOpenPositionInstructionDataDecoder(): FixedSizeDecoder<OpenPositionInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["id", fixDecoderSize(getBytesDecoder(), 32)],
		["side", getSideDecoder()],
		["premiumAmount", getU64Decoder()],
		["positionId", fixDecoderSize(getBytesDecoder(), 32)],
		["settleDelayEpochsSecs", getU32Decoder()],
		["boundaryPrice", getI64Decoder()],
		["price", getI64Decoder()],
		["pricePublishTime", getI64Decoder()],
		["mode", getPositionModeDecoder()]
	])
}

export function getOpenPositionInstructionDataCodec(): FixedSizeCodec<
	OpenPositionInstructionDataArgs,
	OpenPositionInstructionData
> {
	return combineCodec(
		getOpenPositionInstructionDataEncoder(),
		getOpenPositionInstructionDataDecoder()
	)
}

export type OpenPositionAsyncInput<
	TAccountMarket extends string = string,
	TAccountPosition extends string = string,
	TAccountMint extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountVault extends string = string,
	TAccountPool extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountUser extends string = string,
	TAccountPayer extends string = string,
	TAccountBackAuthority extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market?: Address<TAccountMarket>
	position?: Address<TAccountPosition>
	mint: Address<TAccountMint>
	userTokenAccount: Address<TAccountUserTokenAccount>
	vault?: Address<TAccountVault>
	pool?: Address<TAccountPool>
	vaultTokenAccount?: Address<TAccountVaultTokenAccount>
	user: TransactionSigner<TAccountUser>
	payer: TransactionSigner<TAccountPayer>
	backAuthority: TransactionSigner<TAccountBackAuthority>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	id: OpenPositionInstructionDataArgs["id"]
	side: OpenPositionInstructionDataArgs["side"]
	premiumAmount: OpenPositionInstructionDataArgs["premiumAmount"]
	positionId: OpenPositionInstructionDataArgs["positionId"]
	settleDelayEpochsSecs: OpenPositionInstructionDataArgs["settleDelayEpochsSecs"]
	boundaryPrice: OpenPositionInstructionDataArgs["boundaryPrice"]
	price: OpenPositionInstructionDataArgs["price"]
	pricePublishTime: OpenPositionInstructionDataArgs["pricePublishTime"]
	mode: OpenPositionInstructionDataArgs["mode"]
}

export async function getOpenPositionInstructionAsync<
	TAccountMarket extends string,
	TAccountPosition extends string,
	TAccountMint extends string,
	TAccountUserTokenAccount extends string,
	TAccountVault extends string,
	TAccountPool extends string,
	TAccountVaultTokenAccount extends string,
	TAccountUser extends string,
	TAccountPayer extends string,
	TAccountBackAuthority extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: OpenPositionAsyncInput<
		TAccountMarket,
		TAccountPosition,
		TAccountMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountVaultTokenAccount,
		TAccountUser,
		TAccountPayer,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	OpenPositionInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountPosition,
		TAccountMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountVaultTokenAccount,
		TAccountUser,
		TAccountPayer,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		position: { value: input.position ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		vault: { value: input.vault ?? null, isWritable: true },
		pool: { value: input.pool ?? null, isWritable: true },
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		user: { value: input.user ?? null, isWritable: false },
		payer: { value: input.payer ?? null, isWritable: true },
		backAuthority: { value: input.backAuthority ?? null, isWritable: false },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.market.value) {
		accounts.market.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 114, 107,
						101, 116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id))
			]
		})
	}
	if (!accounts.position.value) {
		accounts.position.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 115, 105,
						116, 105, 111, 110, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.user.value)),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id)),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.positionId))
			]
		})
	}
	if (!accounts.vault.value) {
		accounts.vault.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.pool.value) {
		accounts.pool.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.vaultTokenAccount.value) {
		accounts.vaultTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.vault.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.position),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.user),
			getAccountMeta(accounts.payer),
			getAccountMeta(accounts.backAuthority),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getOpenPositionInstructionDataEncoder().encode(args as OpenPositionInstructionDataArgs),
		programAddress
	} as OpenPositionInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountPosition,
		TAccountMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountVaultTokenAccount,
		TAccountUser,
		TAccountPayer,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type OpenPositionInput<
	TAccountMarket extends string = string,
	TAccountPosition extends string = string,
	TAccountMint extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountVault extends string = string,
	TAccountPool extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountUser extends string = string,
	TAccountPayer extends string = string,
	TAccountBackAuthority extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market: Address<TAccountMarket>
	position: Address<TAccountPosition>
	mint: Address<TAccountMint>
	userTokenAccount: Address<TAccountUserTokenAccount>
	vault: Address<TAccountVault>
	pool: Address<TAccountPool>
	vaultTokenAccount: Address<TAccountVaultTokenAccount>
	user: TransactionSigner<TAccountUser>
	payer: TransactionSigner<TAccountPayer>
	backAuthority: TransactionSigner<TAccountBackAuthority>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	id: OpenPositionInstructionDataArgs["id"]
	side: OpenPositionInstructionDataArgs["side"]
	premiumAmount: OpenPositionInstructionDataArgs["premiumAmount"]
	positionId: OpenPositionInstructionDataArgs["positionId"]
	settleDelayEpochsSecs: OpenPositionInstructionDataArgs["settleDelayEpochsSecs"]
	boundaryPrice: OpenPositionInstructionDataArgs["boundaryPrice"]
	price: OpenPositionInstructionDataArgs["price"]
	pricePublishTime: OpenPositionInstructionDataArgs["pricePublishTime"]
	mode: OpenPositionInstructionDataArgs["mode"]
}

export function getOpenPositionInstruction<
	TAccountMarket extends string,
	TAccountPosition extends string,
	TAccountMint extends string,
	TAccountUserTokenAccount extends string,
	TAccountVault extends string,
	TAccountPool extends string,
	TAccountVaultTokenAccount extends string,
	TAccountUser extends string,
	TAccountPayer extends string,
	TAccountBackAuthority extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: OpenPositionInput<
		TAccountMarket,
		TAccountPosition,
		TAccountMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountVaultTokenAccount,
		TAccountUser,
		TAccountPayer,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): OpenPositionInstruction<
	TProgramAddress,
	TAccountMarket,
	TAccountPosition,
	TAccountMint,
	TAccountUserTokenAccount,
	TAccountVault,
	TAccountPool,
	TAccountVaultTokenAccount,
	TAccountUser,
	TAccountPayer,
	TAccountBackAuthority,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		position: { value: input.position ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		vault: { value: input.vault ?? null, isWritable: true },
		pool: { value: input.pool ?? null, isWritable: true },
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		user: { value: input.user ?? null, isWritable: false },
		payer: { value: input.payer ?? null, isWritable: true },
		backAuthority: { value: input.backAuthority ?? null, isWritable: false },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.position),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.user),
			getAccountMeta(accounts.payer),
			getAccountMeta(accounts.backAuthority),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getOpenPositionInstructionDataEncoder().encode(args as OpenPositionInstructionDataArgs),
		programAddress
	} as OpenPositionInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountPosition,
		TAccountMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountVaultTokenAccount,
		TAccountUser,
		TAccountPayer,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedOpenPositionInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		market: TAccountMetas[0]
		position: TAccountMetas[1]
		mint: TAccountMetas[2]
		userTokenAccount: TAccountMetas[3]
		vault: TAccountMetas[4]
		pool: TAccountMetas[5]
		vaultTokenAccount: TAccountMetas[6]
		user: TAccountMetas[7]
		payer: TAccountMetas[8]
		backAuthority: TAccountMetas[9]
		tokenProgram: TAccountMetas[10]
		systemProgram: TAccountMetas[11]
	}
	data: OpenPositionInstructionData
}

export function parseOpenPositionInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedOpenPositionInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 12) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			position: getNextAccount(),
			mint: getNextAccount(),
			userTokenAccount: getNextAccount(),
			vault: getNextAccount(),
			pool: getNextAccount(),
			vaultTokenAccount: getNextAccount(),
			user: getNextAccount(),
			payer: getNextAccount(),
			backAuthority: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getOpenPositionInstructionDataDecoder().decode(instruction.data)
	}
}
