/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressEncoder,
	getBooleanDecoder,
	getBooleanEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, expectSome, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const PAUSE_MARKET_DISCRIMINATOR = new Uint8Array([216, 238, 4, 164, 65, 11, 162, 91])

export function getPauseMarketDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(PAUSE_MARKET_DISCRIMINATOR)
}

export type PauseMarketInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountMaster extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? WritableAccount<TAccountMarket> : TAccountMarket,
			TAccountMasterAccount extends string
				? ReadonlyAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountMaster extends string
				? WritableSignerAccount<TAccountMaster> & AccountSignerMeta<TAccountMaster>
				: TAccountMaster,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type PauseMarketInstructionData = {
	discriminator: ReadonlyUint8Array
	id: ReadonlyUint8Array
	paused: boolean
}

export type PauseMarketInstructionDataArgs = {
	id: ReadonlyUint8Array
	paused: boolean
}

export function getPauseMarketInstructionDataEncoder(): FixedSizeEncoder<PauseMarketInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["id", fixEncoderSize(getBytesEncoder(), 32)],
			["paused", getBooleanEncoder()]
		]),
		value => ({ ...value, discriminator: PAUSE_MARKET_DISCRIMINATOR })
	)
}

export function getPauseMarketInstructionDataDecoder(): FixedSizeDecoder<PauseMarketInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["id", fixDecoderSize(getBytesDecoder(), 32)],
		["paused", getBooleanDecoder()]
	])
}

export function getPauseMarketInstructionDataCodec(): FixedSizeCodec<
	PauseMarketInstructionDataArgs,
	PauseMarketInstructionData
> {
	return combineCodec(
		getPauseMarketInstructionDataEncoder(),
		getPauseMarketInstructionDataDecoder()
	)
}

export type PauseMarketAsyncInput<
	TAccountMarket extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market?: Address<TAccountMarket>
	masterAccount?: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	id: PauseMarketInstructionDataArgs["id"]
	paused: PauseMarketInstructionDataArgs["paused"]
}

export async function getPauseMarketInstructionAsync<
	TAccountMarket extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: PauseMarketAsyncInput<
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	PauseMarketInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.market.value) {
		accounts.market.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 114, 107,
						101, 116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.master.value)),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id))
			]
		})
	}
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getPauseMarketInstructionDataEncoder().encode(args as PauseMarketInstructionDataArgs),
		programAddress
	} as PauseMarketInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type PauseMarketInput<
	TAccountMarket extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market: Address<TAccountMarket>
	masterAccount: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	id: PauseMarketInstructionDataArgs["id"]
	paused: PauseMarketInstructionDataArgs["paused"]
}

export function getPauseMarketInstruction<
	TAccountMarket extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: PauseMarketInput<
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): PauseMarketInstruction<
	TProgramAddress,
	TAccountMarket,
	TAccountMasterAccount,
	TAccountMaster,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getPauseMarketInstructionDataEncoder().encode(args as PauseMarketInstructionDataArgs),
		programAddress
	} as PauseMarketInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type ParsedPauseMarketInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		market: TAccountMetas[0]
		masterAccount: TAccountMetas[1]
		master: TAccountMetas[2]
		systemProgram: TAccountMetas[3]
	}
	data: PauseMarketInstructionData
}

export function parsePauseMarketInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedPauseMarketInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			masterAccount: getNextAccount(),
			master: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getPauseMarketInstructionDataDecoder().decode(instruction.data)
	}
}
