/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getF64Decoder,
	getF64Encoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectSome, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const RESET_IV_DISCRIMINATOR = new Uint8Array([3, 183, 10, 208, 52, 72, 61, 53])

export function getResetIvDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(RESET_IV_DISCRIMINATOR)
}

export type ResetIvInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountOperator extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? WritableAccount<TAccountMarket> : TAccountMarket,
			TAccountOperator extends string
				? WritableSignerAccount<TAccountOperator> & AccountSignerMeta<TAccountOperator>
				: TAccountOperator,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type ResetIvInstructionData = {
	discriminator: ReadonlyUint8Array
	id: ReadonlyUint8Array
	newIv: number
}

export type ResetIvInstructionDataArgs = {
	id: ReadonlyUint8Array
	newIv: number
}

export function getResetIvInstructionDataEncoder(): FixedSizeEncoder<ResetIvInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["id", fixEncoderSize(getBytesEncoder(), 32)],
			["newIv", getF64Encoder()]
		]),
		value => ({ ...value, discriminator: RESET_IV_DISCRIMINATOR })
	)
}

export function getResetIvInstructionDataDecoder(): FixedSizeDecoder<ResetIvInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["id", fixDecoderSize(getBytesDecoder(), 32)],
		["newIv", getF64Decoder()]
	])
}

export function getResetIvInstructionDataCodec(): FixedSizeCodec<
	ResetIvInstructionDataArgs,
	ResetIvInstructionData
> {
	return combineCodec(getResetIvInstructionDataEncoder(), getResetIvInstructionDataDecoder())
}

export type ResetIvAsyncInput<
	TAccountMarket extends string = string,
	TAccountOperator extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market?: Address<TAccountMarket>
	operator: TransactionSigner<TAccountOperator>
	systemProgram?: Address<TAccountSystemProgram>
	id: ResetIvInstructionDataArgs["id"]
	newIv: ResetIvInstructionDataArgs["newIv"]
}

export async function getResetIvInstructionAsync<
	TAccountMarket extends string,
	TAccountOperator extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: ResetIvAsyncInput<TAccountMarket, TAccountOperator, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	ResetIvInstruction<TProgramAddress, TAccountMarket, TAccountOperator, TAccountSystemProgram>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		operator: { value: input.operator ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.market.value) {
		accounts.market.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 114, 107,
						101, 116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id))
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.systemProgram)
		],
		data: getResetIvInstructionDataEncoder().encode(args as ResetIvInstructionDataArgs),
		programAddress
	} as ResetIvInstruction<TProgramAddress, TAccountMarket, TAccountOperator, TAccountSystemProgram>)
}

export type ResetIvInput<
	TAccountMarket extends string = string,
	TAccountOperator extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market: Address<TAccountMarket>
	operator: TransactionSigner<TAccountOperator>
	systemProgram?: Address<TAccountSystemProgram>
	id: ResetIvInstructionDataArgs["id"]
	newIv: ResetIvInstructionDataArgs["newIv"]
}

export function getResetIvInstruction<
	TAccountMarket extends string,
	TAccountOperator extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: ResetIvInput<TAccountMarket, TAccountOperator, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): ResetIvInstruction<TProgramAddress, TAccountMarket, TAccountOperator, TAccountSystemProgram> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		operator: { value: input.operator ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.systemProgram)
		],
		data: getResetIvInstructionDataEncoder().encode(args as ResetIvInstructionDataArgs),
		programAddress
	} as ResetIvInstruction<TProgramAddress, TAccountMarket, TAccountOperator, TAccountSystemProgram>)
}

export type ParsedResetIvInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		market: TAccountMetas[0]
		operator: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: ResetIvInstructionData
}

export function parseResetIvInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedResetIvInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			operator: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getResetIvInstructionDataDecoder().decode(instruction.data)
	}
}
