/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressDecoder,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getI64Decoder,
	getI64Encoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, expectSome, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const SETTLE_POSITION_DISCRIMINATOR = new Uint8Array([33, 156, 74, 218, 215, 42, 112, 175])

export function getSettlePositionDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(SETTLE_POSITION_DISCRIMINATOR)
}

export type SettlePositionInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountPosition extends string | AccountMeta<string> = string,
	TAccountTokenMint extends string | AccountMeta<string> = string,
	TAccountUserTokenAccount extends string | AccountMeta<string> = string,
	TAccountVault extends string | AccountMeta<string> = string,
	TAccountPool extends string | AccountMeta<string> = string,
	TAccountPoolTokenAccount extends string | AccountMeta<string> = string,
	TAccountVaultTokenAccount extends string | AccountMeta<string> = string,
	TAccountOperator extends string | AccountMeta<string> = string,
	TAccountBackAuthority extends string | AccountMeta<string> = string,
	TAccountFeeProvider extends string | AccountMeta<string> = string,
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? ReadonlyAccount<TAccountMarket> : TAccountMarket,
			TAccountPosition extends string ? WritableAccount<TAccountPosition> : TAccountPosition,
			TAccountTokenMint extends string ? ReadonlyAccount<TAccountTokenMint> : TAccountTokenMint,
			TAccountUserTokenAccount extends string
				? WritableAccount<TAccountUserTokenAccount>
				: TAccountUserTokenAccount,
			TAccountVault extends string ? WritableAccount<TAccountVault> : TAccountVault,
			TAccountPool extends string ? WritableAccount<TAccountPool> : TAccountPool,
			TAccountPoolTokenAccount extends string
				? WritableAccount<TAccountPoolTokenAccount>
				: TAccountPoolTokenAccount,
			TAccountVaultTokenAccount extends string
				? WritableAccount<TAccountVaultTokenAccount>
				: TAccountVaultTokenAccount,
			TAccountOperator extends string
				? WritableSignerAccount<TAccountOperator> & AccountSignerMeta<TAccountOperator>
				: TAccountOperator,
			TAccountBackAuthority extends string
				? ReadonlySignerAccount<TAccountBackAuthority> & AccountSignerMeta<TAccountBackAuthority>
				: TAccountBackAuthority,
			TAccountFeeProvider extends string
				? WritableAccount<TAccountFeeProvider>
				: TAccountFeeProvider,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type SettlePositionInstructionData = {
	discriminator: ReadonlyUint8Array
	id: ReadonlyUint8Array
	user: Address
	positionId: ReadonlyUint8Array
	price: bigint
	pricePublishTime: bigint
}

export type SettlePositionInstructionDataArgs = {
	id: ReadonlyUint8Array
	user: Address
	positionId: ReadonlyUint8Array
	price: number | bigint
	pricePublishTime: number | bigint
}

export function getSettlePositionInstructionDataEncoder(): FixedSizeEncoder<SettlePositionInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["id", fixEncoderSize(getBytesEncoder(), 32)],
			["user", getAddressEncoder()],
			["positionId", fixEncoderSize(getBytesEncoder(), 32)],
			["price", getI64Encoder()],
			["pricePublishTime", getI64Encoder()]
		]),
		value => ({ ...value, discriminator: SETTLE_POSITION_DISCRIMINATOR })
	)
}

export function getSettlePositionInstructionDataDecoder(): FixedSizeDecoder<SettlePositionInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["id", fixDecoderSize(getBytesDecoder(), 32)],
		["user", getAddressDecoder()],
		["positionId", fixDecoderSize(getBytesDecoder(), 32)],
		["price", getI64Decoder()],
		["pricePublishTime", getI64Decoder()]
	])
}

export function getSettlePositionInstructionDataCodec(): FixedSizeCodec<
	SettlePositionInstructionDataArgs,
	SettlePositionInstructionData
> {
	return combineCodec(
		getSettlePositionInstructionDataEncoder(),
		getSettlePositionInstructionDataDecoder()
	)
}

export type SettlePositionAsyncInput<
	TAccountMarket extends string = string,
	TAccountPosition extends string = string,
	TAccountTokenMint extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountVault extends string = string,
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountOperator extends string = string,
	TAccountBackAuthority extends string = string,
	TAccountFeeProvider extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market?: Address<TAccountMarket>
	position?: Address<TAccountPosition>
	tokenMint: Address<TAccountTokenMint>
	userTokenAccount: Address<TAccountUserTokenAccount>
	vault?: Address<TAccountVault>
	pool?: Address<TAccountPool>
	poolTokenAccount?: Address<TAccountPoolTokenAccount>
	vaultTokenAccount?: Address<TAccountVaultTokenAccount>
	operator: TransactionSigner<TAccountOperator>
	backAuthority: TransactionSigner<TAccountBackAuthority>
	feeProvider: Address<TAccountFeeProvider>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	id: SettlePositionInstructionDataArgs["id"]
	user: SettlePositionInstructionDataArgs["user"]
	positionId: SettlePositionInstructionDataArgs["positionId"]
	price: SettlePositionInstructionDataArgs["price"]
	pricePublishTime: SettlePositionInstructionDataArgs["pricePublishTime"]
}

export async function getSettlePositionInstructionAsync<
	TAccountMarket extends string,
	TAccountPosition extends string,
	TAccountTokenMint extends string,
	TAccountUserTokenAccount extends string,
	TAccountVault extends string,
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountVaultTokenAccount extends string,
	TAccountOperator extends string,
	TAccountBackAuthority extends string,
	TAccountFeeProvider extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: SettlePositionAsyncInput<
		TAccountMarket,
		TAccountPosition,
		TAccountTokenMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountFeeProvider,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	SettlePositionInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountPosition,
		TAccountTokenMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountFeeProvider,
		TAccountTokenProgram,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: false },
		position: { value: input.position ?? null, isWritable: true },
		tokenMint: { value: input.tokenMint ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		vault: { value: input.vault ?? null, isWritable: true },
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		operator: { value: input.operator ?? null, isWritable: true },
		backAuthority: { value: input.backAuthority ?? null, isWritable: false },
		feeProvider: { value: input.feeProvider ?? null, isWritable: true },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.market.value) {
		accounts.market.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 114, 107,
						101, 116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id))
			]
		})
	}
	if (!accounts.position.value) {
		accounts.position.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 115, 105,
						116, 105, 111, 110, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectSome(args.user)),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id)),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.positionId))
			]
		})
	}
	if (!accounts.vault.value) {
		accounts.vault.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.pool.value) {
		accounts.pool.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.poolTokenAccount.value) {
		accounts.poolTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.pool.value)),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.vaultTokenAccount.value) {
		accounts.vaultTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.vault.value)),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.position),
			getAccountMeta(accounts.tokenMint),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.backAuthority),
			getAccountMeta(accounts.feeProvider),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getSettlePositionInstructionDataEncoder().encode(
			args as SettlePositionInstructionDataArgs
		),
		programAddress
	} as SettlePositionInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountPosition,
		TAccountTokenMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountFeeProvider,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type SettlePositionInput<
	TAccountMarket extends string = string,
	TAccountPosition extends string = string,
	TAccountTokenMint extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountVault extends string = string,
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountOperator extends string = string,
	TAccountBackAuthority extends string = string,
	TAccountFeeProvider extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market: Address<TAccountMarket>
	position: Address<TAccountPosition>
	tokenMint: Address<TAccountTokenMint>
	userTokenAccount: Address<TAccountUserTokenAccount>
	vault: Address<TAccountVault>
	pool: Address<TAccountPool>
	poolTokenAccount: Address<TAccountPoolTokenAccount>
	vaultTokenAccount: Address<TAccountVaultTokenAccount>
	operator: TransactionSigner<TAccountOperator>
	backAuthority: TransactionSigner<TAccountBackAuthority>
	feeProvider: Address<TAccountFeeProvider>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	id: SettlePositionInstructionDataArgs["id"]
	user: SettlePositionInstructionDataArgs["user"]
	positionId: SettlePositionInstructionDataArgs["positionId"]
	price: SettlePositionInstructionDataArgs["price"]
	pricePublishTime: SettlePositionInstructionDataArgs["pricePublishTime"]
}

export function getSettlePositionInstruction<
	TAccountMarket extends string,
	TAccountPosition extends string,
	TAccountTokenMint extends string,
	TAccountUserTokenAccount extends string,
	TAccountVault extends string,
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountVaultTokenAccount extends string,
	TAccountOperator extends string,
	TAccountBackAuthority extends string,
	TAccountFeeProvider extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: SettlePositionInput<
		TAccountMarket,
		TAccountPosition,
		TAccountTokenMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountFeeProvider,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): SettlePositionInstruction<
	TProgramAddress,
	TAccountMarket,
	TAccountPosition,
	TAccountTokenMint,
	TAccountUserTokenAccount,
	TAccountVault,
	TAccountPool,
	TAccountPoolTokenAccount,
	TAccountVaultTokenAccount,
	TAccountOperator,
	TAccountBackAuthority,
	TAccountFeeProvider,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: false },
		position: { value: input.position ?? null, isWritable: true },
		tokenMint: { value: input.tokenMint ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		vault: { value: input.vault ?? null, isWritable: true },
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		operator: { value: input.operator ?? null, isWritable: true },
		backAuthority: { value: input.backAuthority ?? null, isWritable: false },
		feeProvider: { value: input.feeProvider ?? null, isWritable: true },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.position),
			getAccountMeta(accounts.tokenMint),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.backAuthority),
			getAccountMeta(accounts.feeProvider),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getSettlePositionInstructionDataEncoder().encode(
			args as SettlePositionInstructionDataArgs
		),
		programAddress
	} as SettlePositionInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountPosition,
		TAccountTokenMint,
		TAccountUserTokenAccount,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountFeeProvider,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedSettlePositionInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		market: TAccountMetas[0]
		position: TAccountMetas[1]
		tokenMint: TAccountMetas[2]
		userTokenAccount: TAccountMetas[3]
		vault: TAccountMetas[4]
		pool: TAccountMetas[5]
		poolTokenAccount: TAccountMetas[6]
		vaultTokenAccount: TAccountMetas[7]
		operator: TAccountMetas[8]
		backAuthority: TAccountMetas[9]
		feeProvider: TAccountMetas[10]
		tokenProgram: TAccountMetas[11]
		systemProgram: TAccountMetas[12]
	}
	data: SettlePositionInstructionData
}

export function parseSettlePositionInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedSettlePositionInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 13) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			position: getNextAccount(),
			tokenMint: getNextAccount(),
			userTokenAccount: getNextAccount(),
			vault: getNextAccount(),
			pool: getNextAccount(),
			poolTokenAccount: getNextAccount(),
			vaultTokenAccount: getNextAccount(),
			operator: getNextAccount(),
			backAuthority: getNextAccount(),
			feeProvider: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getSettlePositionInstructionDataDecoder().decode(instruction.data)
	}
}
