/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressDecoder,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const TRANSFER_OWNERSHIP_DISCRIMINATOR = new Uint8Array([65, 177, 215, 73, 53, 45, 99, 47])

export function getTransferOwnershipDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(TRANSFER_OWNERSHIP_DISCRIMINATOR)
}

export type TransferOwnershipInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountMaster extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMasterAccount extends string
				? WritableAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountMaster extends string
				? WritableSignerAccount<TAccountMaster> & AccountSignerMeta<TAccountMaster>
				: TAccountMaster,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type TransferOwnershipInstructionData = {
	discriminator: ReadonlyUint8Array
	newMaster: Address
}

export type TransferOwnershipInstructionDataArgs = { newMaster: Address }

export function getTransferOwnershipInstructionDataEncoder(): FixedSizeEncoder<TransferOwnershipInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["newMaster", getAddressEncoder()]
		]),
		value => ({ ...value, discriminator: TRANSFER_OWNERSHIP_DISCRIMINATOR })
	)
}

export function getTransferOwnershipInstructionDataDecoder(): FixedSizeDecoder<TransferOwnershipInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["newMaster", getAddressDecoder()]
	])
}

export function getTransferOwnershipInstructionDataCodec(): FixedSizeCodec<
	TransferOwnershipInstructionDataArgs,
	TransferOwnershipInstructionData
> {
	return combineCodec(
		getTransferOwnershipInstructionDataEncoder(),
		getTransferOwnershipInstructionDataDecoder()
	)
}

export type TransferOwnershipAsyncInput<
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	masterAccount?: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	newMaster: TransferOwnershipInstructionDataArgs["newMaster"]
}

export async function getTransferOwnershipInstructionAsync<
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: TransferOwnershipAsyncInput<TAccountMasterAccount, TAccountMaster, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	TransferOwnershipInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		masterAccount: { value: input.masterAccount ?? null, isWritable: true },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getTransferOwnershipInstructionDataEncoder().encode(
			args as TransferOwnershipInstructionDataArgs
		),
		programAddress
	} as TransferOwnershipInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type TransferOwnershipInput<
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	masterAccount: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	newMaster: TransferOwnershipInstructionDataArgs["newMaster"]
}

export function getTransferOwnershipInstruction<
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: TransferOwnershipInput<TAccountMasterAccount, TAccountMaster, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): TransferOwnershipInstruction<
	TProgramAddress,
	TAccountMasterAccount,
	TAccountMaster,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		masterAccount: { value: input.masterAccount ?? null, isWritable: true },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getTransferOwnershipInstructionDataEncoder().encode(
			args as TransferOwnershipInstructionDataArgs
		),
		programAddress
	} as TransferOwnershipInstruction<
		TProgramAddress,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type ParsedTransferOwnershipInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		masterAccount: TAccountMetas[0]
		master: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: TransferOwnershipInstructionData
}

export function parseTransferOwnershipInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedTransferOwnershipInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			masterAccount: getNextAccount(),
			master: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getTransferOwnershipInstructionDataDecoder().decode(instruction.data)
	}
}
