/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const WITHDRAW_POOL_DISCRIMINATOR = new Uint8Array([190, 43, 148, 248, 68, 5, 215, 136])

export function getWithdrawPoolDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(WITHDRAW_POOL_DISCRIMINATOR)
}

export type WithdrawPoolInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountPool extends string | AccountMeta<string> = string,
	TAccountPoolTokenAccount extends string | AccountMeta<string> = string,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountUserTokenAccount extends string | AccountMeta<string> = string,
	TAccountMaster extends string | AccountMeta<string> = string,
	TAccountMint extends string | AccountMeta<string> = string,
	TAccountAssociatedTokenProgram extends
		| string
		| AccountMeta<string> = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPool extends string ? WritableAccount<TAccountPool> : TAccountPool,
			TAccountPoolTokenAccount extends string
				? WritableAccount<TAccountPoolTokenAccount>
				: TAccountPoolTokenAccount,
			TAccountMasterAccount extends string
				? ReadonlyAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountUserTokenAccount extends string
				? WritableAccount<TAccountUserTokenAccount>
				: TAccountUserTokenAccount,
			TAccountMaster extends string
				? WritableSignerAccount<TAccountMaster> & AccountSignerMeta<TAccountMaster>
				: TAccountMaster,
			TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint,
			TAccountAssociatedTokenProgram extends string
				? ReadonlyAccount<TAccountAssociatedTokenProgram>
				: TAccountAssociatedTokenProgram,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type WithdrawPoolInstructionData = {
	discriminator: ReadonlyUint8Array
	amount: bigint
}

export type WithdrawPoolInstructionDataArgs = { amount: number | bigint }

export function getWithdrawPoolInstructionDataEncoder(): FixedSizeEncoder<WithdrawPoolInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["amount", getU64Encoder()]
		]),
		value => ({ ...value, discriminator: WITHDRAW_POOL_DISCRIMINATOR })
	)
}

export function getWithdrawPoolInstructionDataDecoder(): FixedSizeDecoder<WithdrawPoolInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["amount", getU64Decoder()]
	])
}

export function getWithdrawPoolInstructionDataCodec(): FixedSizeCodec<
	WithdrawPoolInstructionDataArgs,
	WithdrawPoolInstructionData
> {
	return combineCodec(
		getWithdrawPoolInstructionDataEncoder(),
		getWithdrawPoolInstructionDataDecoder()
	)
}

export type WithdrawPoolAsyncInput<
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountMint extends string = string,
	TAccountAssociatedTokenProgram extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	pool?: Address<TAccountPool>
	poolTokenAccount?: Address<TAccountPoolTokenAccount>
	masterAccount?: Address<TAccountMasterAccount>
	userTokenAccount?: Address<TAccountUserTokenAccount>
	master: TransactionSigner<TAccountMaster>
	mint: Address<TAccountMint>
	associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	amount: WithdrawPoolInstructionDataArgs["amount"]
}

export async function getWithdrawPoolInstructionAsync<
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountMasterAccount extends string,
	TAccountUserTokenAccount extends string,
	TAccountMaster extends string,
	TAccountMint extends string,
	TAccountAssociatedTokenProgram extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: WithdrawPoolAsyncInput<
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	WithdrawPoolInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		master: { value: input.master ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		associatedTokenProgram: {
			value: input.associatedTokenProgram ?? null,
			isWritable: false
		},
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.pool.value) {
		accounts.pool.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.poolTokenAccount.value) {
		accounts.poolTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.pool.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.userTokenAccount.value) {
		accounts.userTokenAccount.value = await getProgramDerivedAddress({
			programAddress:
				"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
			seeds: [
				getAddressEncoder().encode(expectAddress(accounts.master.value)),
				getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.associatedTokenProgram.value) {
		accounts.associatedTokenProgram.value =
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.associatedTokenProgram),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getWithdrawPoolInstructionDataEncoder().encode(args as WithdrawPoolInstructionDataArgs),
		programAddress
	} as WithdrawPoolInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type WithdrawPoolInput<
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountMint extends string = string,
	TAccountAssociatedTokenProgram extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	pool: Address<TAccountPool>
	poolTokenAccount: Address<TAccountPoolTokenAccount>
	masterAccount: Address<TAccountMasterAccount>
	userTokenAccount: Address<TAccountUserTokenAccount>
	master: TransactionSigner<TAccountMaster>
	mint: Address<TAccountMint>
	associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	amount: WithdrawPoolInstructionDataArgs["amount"]
}

export function getWithdrawPoolInstruction<
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountMasterAccount extends string,
	TAccountUserTokenAccount extends string,
	TAccountMaster extends string,
	TAccountMint extends string,
	TAccountAssociatedTokenProgram extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: WithdrawPoolInput<
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): WithdrawPoolInstruction<
	TProgramAddress,
	TAccountPool,
	TAccountPoolTokenAccount,
	TAccountMasterAccount,
	TAccountUserTokenAccount,
	TAccountMaster,
	TAccountMint,
	TAccountAssociatedTokenProgram,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		master: { value: input.master ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		associatedTokenProgram: {
			value: input.associatedTokenProgram ?? null,
			isWritable: false
		},
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.associatedTokenProgram.value) {
		accounts.associatedTokenProgram.value =
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.associatedTokenProgram),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getWithdrawPoolInstructionDataEncoder().encode(args as WithdrawPoolInstructionDataArgs),
		programAddress
	} as WithdrawPoolInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedWithdrawPoolInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		pool: TAccountMetas[0]
		poolTokenAccount: TAccountMetas[1]
		masterAccount: TAccountMetas[2]
		userTokenAccount: TAccountMetas[3]
		master: TAccountMetas[4]
		mint: TAccountMetas[5]
		associatedTokenProgram: TAccountMetas[6]
		tokenProgram: TAccountMetas[7]
		systemProgram: TAccountMetas[8]
	}
	data: WithdrawPoolInstructionData
}

export function parseWithdrawPoolInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedWithdrawPoolInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 9) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			pool: getNextAccount(),
			poolTokenAccount: getNextAccount(),
			masterAccount: getNextAccount(),
			userTokenAccount: getNextAccount(),
			master: getNextAccount(),
			mint: getNextAccount(),
			associatedTokenProgram: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getWithdrawPoolInstructionDataDecoder().decode(instruction.data)
	}
}
