/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getBooleanDecoder,
	getBooleanEncoder,
	getStructDecoder,
	getStructEncoder
} from "@solana/kit"

export type MarketPaused = { market: Address; paused: boolean }

export type MarketPausedArgs = MarketPaused

export function getMarketPausedEncoder(): FixedSizeEncoder<MarketPausedArgs> {
	return getStructEncoder([
		["market", getAddressEncoder()],
		["paused", getBooleanEncoder()]
	])
}

export function getMarketPausedDecoder(): FixedSizeDecoder<MarketPaused> {
	return getStructDecoder([
		["market", getAddressDecoder()],
		["paused", getBooleanDecoder()]
	])
}

export function getMarketPausedCodec(): FixedSizeCodec<MarketPausedArgs, MarketPaused> {
	return combineCodec(getMarketPausedEncoder(), getMarketPausedDecoder())
}
