/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder
} from "@solana/kit"

export type MarketConfigUpdated = { market: Address; authority: Address }

export type MarketConfigUpdatedArgs = MarketConfigUpdated

export function getMarketConfigUpdatedEncoder(): FixedSizeEncoder<MarketConfigUpdatedArgs> {
	return getStructEncoder([
		["market", getAddressEncoder()],
		["authority", getAddressEncoder()]
	])
}

export function getMarketConfigUpdatedDecoder(): FixedSizeDecoder<MarketConfigUpdated> {
	return getStructDecoder([
		["market", getAddressDecoder()],
		["authority", getAddressDecoder()]
	])
}

export function getMarketConfigUpdatedCodec(): FixedSizeCodec<
	MarketConfigUpdatedArgs,
	MarketConfigUpdated
> {
	return combineCodec(getMarketConfigUpdatedEncoder(), getMarketConfigUpdatedDecoder())
}
