/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type MasterWithdrawn = {
	master: Address
	tokenMint: Address
	amount: bigint
}

export type MasterWithdrawnArgs = {
	master: Address
	tokenMint: Address
	amount: number | bigint
}

export function getMasterWithdrawnEncoder(): FixedSizeEncoder<MasterWithdrawnArgs> {
	return getStructEncoder([
		["master", getAddressEncoder()],
		["tokenMint", getAddressEncoder()],
		["amount", getU64Encoder()]
	])
}

export function getMasterWithdrawnDecoder(): FixedSizeDecoder<MasterWithdrawn> {
	return getStructDecoder([
		["master", getAddressDecoder()],
		["tokenMint", getAddressDecoder()],
		["amount", getU64Decoder()]
	])
}

export function getMasterWithdrawnCodec(): FixedSizeCodec<MasterWithdrawnArgs, MasterWithdrawn> {
	return combineCodec(getMasterWithdrawnEncoder(), getMasterWithdrawnDecoder())
}
