/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder
} from "@solana/kit"

export type OwnershipTransferAccepted = {
	previousMaster: Address
	newMaster: Address
}

export type OwnershipTransferAcceptedArgs = OwnershipTransferAccepted

export function getOwnershipTransferAcceptedEncoder(): FixedSizeEncoder<OwnershipTransferAcceptedArgs> {
	return getStructEncoder([
		["previousMaster", getAddressEncoder()],
		["newMaster", getAddressEncoder()]
	])
}

export function getOwnershipTransferAcceptedDecoder(): FixedSizeDecoder<OwnershipTransferAccepted> {
	return getStructDecoder([
		["previousMaster", getAddressDecoder()],
		["newMaster", getAddressDecoder()]
	])
}

export function getOwnershipTransferAcceptedCodec(): FixedSizeCodec<
	OwnershipTransferAcceptedArgs,
	OwnershipTransferAccepted
> {
	return combineCodec(getOwnershipTransferAcceptedEncoder(), getOwnershipTransferAcceptedDecoder())
}
