/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder
} from "@solana/kit"

export type OwnershipTransferStarted = {
	previousMaster: Address
	newMaster: Address
}

export type OwnershipTransferStartedArgs = OwnershipTransferStarted

export function getOwnershipTransferStartedEncoder(): FixedSizeEncoder<OwnershipTransferStartedArgs> {
	return getStructEncoder([
		["previousMaster", getAddressEncoder()],
		["newMaster", getAddressEncoder()]
	])
}

export function getOwnershipTransferStartedDecoder(): FixedSizeDecoder<OwnershipTransferStarted> {
	return getStructDecoder([
		["previousMaster", getAddressDecoder()],
		["newMaster", getAddressDecoder()]
	])
}

export function getOwnershipTransferStartedCodec(): FixedSizeCodec<
	OwnershipTransferStartedArgs,
	OwnershipTransferStarted
> {
	return combineCodec(getOwnershipTransferStartedEncoder(), getOwnershipTransferStartedDecoder())
}
