/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type PoolFunded = { pool: Address; funder: Address; amount: bigint }

export type PoolFundedArgs = {
	pool: Address
	funder: Address
	amount: number | bigint
}

export function getPoolFundedEncoder(): FixedSizeEncoder<PoolFundedArgs> {
	return getStructEncoder([
		["pool", getAddressEncoder()],
		["funder", getAddressEncoder()],
		["amount", getU64Encoder()]
	])
}

export function getPoolFundedDecoder(): FixedSizeDecoder<PoolFunded> {
	return getStructDecoder([
		["pool", getAddressDecoder()],
		["funder", getAddressDecoder()],
		["amount", getU64Decoder()]
	])
}

export function getPoolFundedCodec(): FixedSizeCodec<PoolFundedArgs, PoolFunded> {
	return combineCodec(getPoolFundedEncoder(), getPoolFundedDecoder())
}
