/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressDecoder,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getF64Decoder,
	getF64Encoder,
	getI64Decoder,
	getI64Encoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	type ReadonlyUint8Array
} from "@solana/kit"
import {
	getPositionModeDecoder,
	getPositionModeEncoder,
	getSideDecoder,
	getSideEncoder,
	type PositionMode,
	type PositionModeArgs,
	type Side,
	type SideArgs
} from "."

export type PositionOpened = {
	id: Address
	feedId: ReadonlyUint8Array
	user: Address
	side: Side
	amount: bigint
	premium: number
	premiumAmount: bigint
	boundaryPrice: number
	spotPrice: number
	multiplier: number
	startTime: bigint
	endTime: bigint
	mode: PositionMode
}

export type PositionOpenedArgs = {
	id: Address
	feedId: ReadonlyUint8Array
	user: Address
	side: SideArgs
	amount: number | bigint
	premium: number
	premiumAmount: number | bigint
	boundaryPrice: number
	spotPrice: number
	multiplier: number
	startTime: number | bigint
	endTime: number | bigint
	mode: PositionModeArgs
}

export function getPositionOpenedEncoder(): FixedSizeEncoder<PositionOpenedArgs> {
	return getStructEncoder([
		["id", getAddressEncoder()],
		["feedId", fixEncoderSize(getBytesEncoder(), 32)],
		["user", getAddressEncoder()],
		["side", getSideEncoder()],
		["amount", getU64Encoder()],
		["premium", getF64Encoder()],
		["premiumAmount", getU64Encoder()],
		["boundaryPrice", getF64Encoder()],
		["spotPrice", getF64Encoder()],
		["multiplier", getF64Encoder()],
		["startTime", getI64Encoder()],
		["endTime", getI64Encoder()],
		["mode", getPositionModeEncoder()]
	])
}

export function getPositionOpenedDecoder(): FixedSizeDecoder<PositionOpened> {
	return getStructDecoder([
		["id", getAddressDecoder()],
		["feedId", fixDecoderSize(getBytesDecoder(), 32)],
		["user", getAddressDecoder()],
		["side", getSideDecoder()],
		["amount", getU64Decoder()],
		["premium", getF64Decoder()],
		["premiumAmount", getU64Decoder()],
		["boundaryPrice", getF64Decoder()],
		["spotPrice", getF64Decoder()],
		["multiplier", getF64Decoder()],
		["startTime", getI64Decoder()],
		["endTime", getI64Decoder()],
		["mode", getPositionModeDecoder()]
	])
}

export function getPositionOpenedCodec(): FixedSizeCodec<PositionOpenedArgs, PositionOpened> {
	return combineCodec(getPositionOpenedEncoder(), getPositionOpenedDecoder())
}
