/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getEnumDecoder,
	getEnumEncoder
} from "@solana/kit"

export enum PositionResult {
	Won,
	Lose,
	Draw,
	Refund
}

export type PositionResultArgs = PositionResult

export function getPositionResultEncoder(): FixedSizeEncoder<PositionResultArgs> {
	return getEnumEncoder(PositionResult)
}

export function getPositionResultDecoder(): FixedSizeDecoder<PositionResult> {
	return getEnumDecoder(PositionResult)
}

export function getPositionResultCodec(): FixedSizeCodec<PositionResultArgs, PositionResult> {
	return combineCodec(getPositionResultEncoder(), getPositionResultDecoder())
}
