/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	getAddressDecoder,
	getAddressEncoder,
	getF64Decoder,
	getF64Encoder,
	getOptionDecoder,
	getOptionEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	type Option,
	type OptionOrNullable
} from "@solana/kit"
import {
	getPositionResultDecoder,
	getPositionResultEncoder,
	getSideDecoder,
	getSideEncoder,
	type PositionResult,
	type PositionResultArgs,
	type Side,
	type SideArgs
} from "."

export type PositionSettled = {
	id: Address
	user: Address
	side: Side
	boundaryPrice: number
	spotPrice: number
	multiplier: number
	finalPrice: Option<number>
	result: PositionResult
	payout: bigint
	premium: bigint
}

export type PositionSettledArgs = {
	id: Address
	user: Address
	side: SideArgs
	boundaryPrice: number
	spotPrice: number
	multiplier: number
	finalPrice: OptionOrNullable<number>
	result: PositionResultArgs
	payout: number | bigint
	premium: number | bigint
}

export function getPositionSettledEncoder(): Encoder<PositionSettledArgs> {
	return getStructEncoder([
		["id", getAddressEncoder()],
		["user", getAddressEncoder()],
		["side", getSideEncoder()],
		["boundaryPrice", getF64Encoder()],
		["spotPrice", getF64Encoder()],
		["multiplier", getF64Encoder()],
		["finalPrice", getOptionEncoder(getF64Encoder())],
		["result", getPositionResultEncoder()],
		["payout", getU64Encoder()],
		["premium", getU64Encoder()]
	])
}

export function getPositionSettledDecoder(): Decoder<PositionSettled> {
	return getStructDecoder([
		["id", getAddressDecoder()],
		["user", getAddressDecoder()],
		["side", getSideDecoder()],
		["boundaryPrice", getF64Decoder()],
		["spotPrice", getF64Decoder()],
		["multiplier", getF64Decoder()],
		["finalPrice", getOptionDecoder(getF64Decoder())],
		["result", getPositionResultDecoder()],
		["payout", getU64Decoder()],
		["premium", getU64Decoder()]
	])
}

export function getPositionSettledCodec(): Codec<PositionSettledArgs, PositionSettled> {
	return combineCodec(getPositionSettledEncoder(), getPositionSettledDecoder())
}
