/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getEnumDecoder,
	getEnumEncoder
} from "@solana/kit"

export enum Side {
	Call,
	Put
}

export type SideArgs = Side

export function getSideEncoder(): FixedSizeEncoder<SideArgs> {
	return getEnumEncoder(Side)
}

export function getSideDecoder(): FixedSizeDecoder<Side> {
	return getEnumDecoder(Side)
}

export function getSideCodec(): FixedSizeCodec<SideArgs, Side> {
	return combineCodec(getSideEncoder(), getSideDecoder())
}
