/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type VaultWithdrawn = {
	vault: Address
	amount: bigint
	destination: Address
}

export type VaultWithdrawnArgs = {
	vault: Address
	amount: number | bigint
	destination: Address
}

export function getVaultWithdrawnEncoder(): FixedSizeEncoder<VaultWithdrawnArgs> {
	return getStructEncoder([
		["vault", getAddressEncoder()],
		["amount", getU64Encoder()],
		["destination", getAddressEncoder()]
	])
}

export function getVaultWithdrawnDecoder(): FixedSizeDecoder<VaultWithdrawn> {
	return getStructDecoder([
		["vault", getAddressDecoder()],
		["amount", getU64Decoder()],
		["destination", getAddressDecoder()]
	])
}

export function getVaultWithdrawnCodec(): FixedSizeCodec<VaultWithdrawnArgs, VaultWithdrawn> {
	return combineCodec(getVaultWithdrawnEncoder(), getVaultWithdrawnDecoder())
}
