/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const FUND_POOL_DISCRIMINATOR = new Uint8Array([36, 57, 233, 176, 181, 20, 87, 159])

export function getFundPoolDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(FUND_POOL_DISCRIMINATOR)
}

export type FundPoolInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountPool extends string | AccountMeta<string> = string,
	TAccountPoolTokenAccount extends string | AccountMeta<string> = string,
	TAccountUserTokenAccount extends string | AccountMeta<string> = string,
	TAccountSigner extends string | AccountMeta<string> = string,
	TAccountMint extends string | AccountMeta<string> = string,
	TAccountAssociatedTokenProgram extends
		| string
		| AccountMeta<string> = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountPool extends string ? WritableAccount<TAccountPool> : TAccountPool,
			TAccountPoolTokenAccount extends string
				? WritableAccount<TAccountPoolTokenAccount>
				: TAccountPoolTokenAccount,
			TAccountUserTokenAccount extends string
				? WritableAccount<TAccountUserTokenAccount>
				: TAccountUserTokenAccount,
			TAccountSigner extends string
				? WritableSignerAccount<TAccountSigner> & AccountSignerMeta<TAccountSigner>
				: TAccountSigner,
			TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint,
			TAccountAssociatedTokenProgram extends string
				? ReadonlyAccount<TAccountAssociatedTokenProgram>
				: TAccountAssociatedTokenProgram,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type FundPoolInstructionData = {
	discriminator: ReadonlyUint8Array
	amount: bigint
}

export type FundPoolInstructionDataArgs = { amount: number | bigint }

export function getFundPoolInstructionDataEncoder(): FixedSizeEncoder<FundPoolInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["amount", getU64Encoder()]
		]),
		value => ({ ...value, discriminator: FUND_POOL_DISCRIMINATOR })
	)
}

export function getFundPoolInstructionDataDecoder(): FixedSizeDecoder<FundPoolInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["amount", getU64Decoder()]
	])
}

export function getFundPoolInstructionDataCodec(): FixedSizeCodec<
	FundPoolInstructionDataArgs,
	FundPoolInstructionData
> {
	return combineCodec(getFundPoolInstructionDataEncoder(), getFundPoolInstructionDataDecoder())
}

export type FundPoolAsyncInput<
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountSigner extends string = string,
	TAccountMint extends string = string,
	TAccountAssociatedTokenProgram extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	pool?: Address<TAccountPool>
	poolTokenAccount?: Address<TAccountPoolTokenAccount>
	userTokenAccount?: Address<TAccountUserTokenAccount>
	signer: TransactionSigner<TAccountSigner>
	mint: Address<TAccountMint>
	associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	amount: FundPoolInstructionDataArgs["amount"]
}

export async function getFundPoolInstructionAsync<
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountUserTokenAccount extends string,
	TAccountSigner extends string,
	TAccountMint extends string,
	TAccountAssociatedTokenProgram extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: FundPoolAsyncInput<
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountUserTokenAccount,
		TAccountSigner,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	FundPoolInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountUserTokenAccount,
		TAccountSigner,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		signer: { value: input.signer ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		associatedTokenProgram: {
			value: input.associatedTokenProgram ?? null,
			isWritable: false
		},
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.pool.value) {
		accounts.pool.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.poolTokenAccount.value) {
		accounts.poolTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.pool.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.userTokenAccount.value) {
		accounts.userTokenAccount.value = await getProgramDerivedAddress({
			programAddress:
				"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
			seeds: [
				getAddressEncoder().encode(expectAddress(accounts.signer.value)),
				getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.associatedTokenProgram.value) {
		accounts.associatedTokenProgram.value =
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.signer),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.associatedTokenProgram),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getFundPoolInstructionDataEncoder().encode(args as FundPoolInstructionDataArgs),
		programAddress
	} as FundPoolInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountUserTokenAccount,
		TAccountSigner,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type FundPoolInput<
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountSigner extends string = string,
	TAccountMint extends string = string,
	TAccountAssociatedTokenProgram extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	pool: Address<TAccountPool>
	poolTokenAccount: Address<TAccountPoolTokenAccount>
	userTokenAccount: Address<TAccountUserTokenAccount>
	signer: TransactionSigner<TAccountSigner>
	mint: Address<TAccountMint>
	associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	amount: FundPoolInstructionDataArgs["amount"]
}

export function getFundPoolInstruction<
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountUserTokenAccount extends string,
	TAccountSigner extends string,
	TAccountMint extends string,
	TAccountAssociatedTokenProgram extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: FundPoolInput<
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountUserTokenAccount,
		TAccountSigner,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): FundPoolInstruction<
	TProgramAddress,
	TAccountPool,
	TAccountPoolTokenAccount,
	TAccountUserTokenAccount,
	TAccountSigner,
	TAccountMint,
	TAccountAssociatedTokenProgram,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		signer: { value: input.signer ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		associatedTokenProgram: {
			value: input.associatedTokenProgram ?? null,
			isWritable: false
		},
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.associatedTokenProgram.value) {
		accounts.associatedTokenProgram.value =
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.signer),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.associatedTokenProgram),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getFundPoolInstructionDataEncoder().encode(args as FundPoolInstructionDataArgs),
		programAddress
	} as FundPoolInstruction<
		TProgramAddress,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountUserTokenAccount,
		TAccountSigner,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedFundPoolInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		pool: TAccountMetas[0]
		poolTokenAccount: TAccountMetas[1]
		userTokenAccount: TAccountMetas[2]
		signer: TAccountMetas[3]
		mint: TAccountMetas[4]
		associatedTokenProgram: TAccountMetas[5]
		tokenProgram: TAccountMetas[6]
		systemProgram: TAccountMetas[7]
	}
	data: FundPoolInstructionData
}

export function parseFundPoolInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedFundPoolInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 8) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			pool: getNextAccount(),
			poolTokenAccount: getNextAccount(),
			userTokenAccount: getNextAccount(),
			signer: getNextAccount(),
			mint: getNextAccount(),
			associatedTokenProgram: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getFundPoolInstructionDataDecoder().decode(instruction.data)
	}
}
