/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getI64Decoder,
	getI64Encoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlySignerAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const SETTLE_MULTIPLE_POSITIONS_DISCRIMINATOR = new Uint8Array([
	225, 3, 116, 19, 38, 154, 191, 245
])

export function getSettleMultiplePositionsDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(SETTLE_MULTIPLE_POSITIONS_DISCRIMINATOR)
}

export type SettleMultiplePositionsInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountTokenMint extends string | AccountMeta<string> = string,
	TAccountVault extends string | AccountMeta<string> = string,
	TAccountPool extends string | AccountMeta<string> = string,
	TAccountPoolTokenAccount extends string | AccountMeta<string> = string,
	TAccountVaultTokenAccount extends string | AccountMeta<string> = string,
	TAccountOperator extends string | AccountMeta<string> = string,
	TAccountBackAuthority extends string | AccountMeta<string> = string,
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? ReadonlyAccount<TAccountMarket> : TAccountMarket,
			TAccountTokenMint extends string ? ReadonlyAccount<TAccountTokenMint> : TAccountTokenMint,
			TAccountVault extends string ? WritableAccount<TAccountVault> : TAccountVault,
			TAccountPool extends string ? WritableAccount<TAccountPool> : TAccountPool,
			TAccountPoolTokenAccount extends string
				? WritableAccount<TAccountPoolTokenAccount>
				: TAccountPoolTokenAccount,
			TAccountVaultTokenAccount extends string
				? WritableAccount<TAccountVaultTokenAccount>
				: TAccountVaultTokenAccount,
			TAccountOperator extends string
				? WritableSignerAccount<TAccountOperator> & AccountSignerMeta<TAccountOperator>
				: TAccountOperator,
			TAccountBackAuthority extends string
				? ReadonlySignerAccount<TAccountBackAuthority> & AccountSignerMeta<TAccountBackAuthority>
				: TAccountBackAuthority,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type SettleMultiplePositionsInstructionData = {
	discriminator: ReadonlyUint8Array
	price: bigint
	pricePublishTime: bigint
}

export type SettleMultiplePositionsInstructionDataArgs = {
	price: number | bigint
	pricePublishTime: number | bigint
}

export function getSettleMultiplePositionsInstructionDataEncoder(): FixedSizeEncoder<SettleMultiplePositionsInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["price", getI64Encoder()],
			["pricePublishTime", getI64Encoder()]
		]),
		value => ({
			...value,
			discriminator: SETTLE_MULTIPLE_POSITIONS_DISCRIMINATOR
		})
	)
}

export function getSettleMultiplePositionsInstructionDataDecoder(): FixedSizeDecoder<SettleMultiplePositionsInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["price", getI64Decoder()],
		["pricePublishTime", getI64Decoder()]
	])
}

export function getSettleMultiplePositionsInstructionDataCodec(): FixedSizeCodec<
	SettleMultiplePositionsInstructionDataArgs,
	SettleMultiplePositionsInstructionData
> {
	return combineCodec(
		getSettleMultiplePositionsInstructionDataEncoder(),
		getSettleMultiplePositionsInstructionDataDecoder()
	)
}

export type SettleMultiplePositionsAsyncInput<
	TAccountMarket extends string = string,
	TAccountTokenMint extends string = string,
	TAccountVault extends string = string,
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountOperator extends string = string,
	TAccountBackAuthority extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	/**
	 * The market account - loaded once for all positions
	 * Note: All positions in a batch must belong to the same market
	 */
	market: Address<TAccountMarket>
	/** Token mint for the pool/vault */
	tokenMint: Address<TAccountTokenMint>
	/** Vault account for premium refunds */
	vault?: Address<TAccountVault>
	/** Pool account for payouts */
	pool?: Address<TAccountPool>
	/** Pool's token account for transfers */
	poolTokenAccount?: Address<TAccountPoolTokenAccount>
	/** Vault's token account for premium refunds */
	vaultTokenAccount?: Address<TAccountVaultTokenAccount>
	/** Operator who can trigger settlements */
	operator: TransactionSigner<TAccountOperator>
	/** Back authority who validates price data */
	backAuthority: TransactionSigner<TAccountBackAuthority>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	price: SettleMultiplePositionsInstructionDataArgs["price"]
	pricePublishTime: SettleMultiplePositionsInstructionDataArgs["pricePublishTime"]
}

export async function getSettleMultiplePositionsInstructionAsync<
	TAccountMarket extends string,
	TAccountTokenMint extends string,
	TAccountVault extends string,
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountVaultTokenAccount extends string,
	TAccountOperator extends string,
	TAccountBackAuthority extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: SettleMultiplePositionsAsyncInput<
		TAccountMarket,
		TAccountTokenMint,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	SettleMultiplePositionsInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountTokenMint,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: false },
		tokenMint: { value: input.tokenMint ?? null, isWritable: false },
		vault: { value: input.vault ?? null, isWritable: true },
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		operator: { value: input.operator ?? null, isWritable: true },
		backAuthority: { value: input.backAuthority ?? null, isWritable: false },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.vault.value) {
		accounts.vault.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.pool.value) {
		accounts.pool.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.poolTokenAccount.value) {
		accounts.poolTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 112, 111, 111, 108,
						95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.pool.value)),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.vaultTokenAccount.value) {
		accounts.vaultTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.vault.value)),
				getAddressEncoder().encode(expectAddress(accounts.tokenMint.value))
			]
		})
	}
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.tokenMint),
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.backAuthority),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getSettleMultiplePositionsInstructionDataEncoder().encode(
			args as SettleMultiplePositionsInstructionDataArgs
		),
		programAddress
	} as SettleMultiplePositionsInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountTokenMint,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type SettleMultiplePositionsInput<
	TAccountMarket extends string = string,
	TAccountTokenMint extends string = string,
	TAccountVault extends string = string,
	TAccountPool extends string = string,
	TAccountPoolTokenAccount extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountOperator extends string = string,
	TAccountBackAuthority extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	/**
	 * The market account - loaded once for all positions
	 * Note: All positions in a batch must belong to the same market
	 */
	market: Address<TAccountMarket>
	/** Token mint for the pool/vault */
	tokenMint: Address<TAccountTokenMint>
	/** Vault account for premium refunds */
	vault: Address<TAccountVault>
	/** Pool account for payouts */
	pool: Address<TAccountPool>
	/** Pool's token account for transfers */
	poolTokenAccount: Address<TAccountPoolTokenAccount>
	/** Vault's token account for premium refunds */
	vaultTokenAccount: Address<TAccountVaultTokenAccount>
	/** Operator who can trigger settlements */
	operator: TransactionSigner<TAccountOperator>
	/** Back authority who validates price data */
	backAuthority: TransactionSigner<TAccountBackAuthority>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	price: SettleMultiplePositionsInstructionDataArgs["price"]
	pricePublishTime: SettleMultiplePositionsInstructionDataArgs["pricePublishTime"]
}

export function getSettleMultiplePositionsInstruction<
	TAccountMarket extends string,
	TAccountTokenMint extends string,
	TAccountVault extends string,
	TAccountPool extends string,
	TAccountPoolTokenAccount extends string,
	TAccountVaultTokenAccount extends string,
	TAccountOperator extends string,
	TAccountBackAuthority extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: SettleMultiplePositionsInput<
		TAccountMarket,
		TAccountTokenMint,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): SettleMultiplePositionsInstruction<
	TProgramAddress,
	TAccountMarket,
	TAccountTokenMint,
	TAccountVault,
	TAccountPool,
	TAccountPoolTokenAccount,
	TAccountVaultTokenAccount,
	TAccountOperator,
	TAccountBackAuthority,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: false },
		tokenMint: { value: input.tokenMint ?? null, isWritable: false },
		vault: { value: input.vault ?? null, isWritable: true },
		pool: { value: input.pool ?? null, isWritable: true },
		poolTokenAccount: {
			value: input.poolTokenAccount ?? null,
			isWritable: true
		},
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		operator: { value: input.operator ?? null, isWritable: true },
		backAuthority: { value: input.backAuthority ?? null, isWritable: false },
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.tokenMint),
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.pool),
			getAccountMeta(accounts.poolTokenAccount),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.backAuthority),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getSettleMultiplePositionsInstructionDataEncoder().encode(
			args as SettleMultiplePositionsInstructionDataArgs
		),
		programAddress
	} as SettleMultiplePositionsInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountTokenMint,
		TAccountVault,
		TAccountPool,
		TAccountPoolTokenAccount,
		TAccountVaultTokenAccount,
		TAccountOperator,
		TAccountBackAuthority,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedSettleMultiplePositionsInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		/**
		 * The market account - loaded once for all positions
		 * Note: All positions in a batch must belong to the same market
		 */
		market: TAccountMetas[0]
		/** Token mint for the pool/vault */
		tokenMint: TAccountMetas[1]
		/** Vault account for premium refunds */
		vault: TAccountMetas[2]
		/** Pool account for payouts */
		pool: TAccountMetas[3]
		/** Pool's token account for transfers */
		poolTokenAccount: TAccountMetas[4]
		/** Vault's token account for premium refunds */
		vaultTokenAccount: TAccountMetas[5]
		/** Operator who can trigger settlements */
		operator: TAccountMetas[6]
		/** Back authority who validates price data */
		backAuthority: TAccountMetas[7]
		tokenProgram: TAccountMetas[8]
		systemProgram: TAccountMetas[9]
	}
	data: SettleMultiplePositionsInstructionData
}

export function parseSettleMultiplePositionsInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedSettleMultiplePositionsInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 10) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			tokenMint: getNextAccount(),
			vault: getNextAccount(),
			pool: getNextAccount(),
			poolTokenAccount: getNextAccount(),
			vaultTokenAccount: getNextAccount(),
			operator: getNextAccount(),
			backAuthority: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getSettleMultiplePositionsInstructionDataDecoder().decode(instruction.data)
	}
}
