/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressDecoder,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectSome, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const TRANSFER_MARKET_OPERATOR_DISCRIMINATOR = new Uint8Array([
	205, 70, 53, 252, 53, 239, 214, 31
])

export function getTransferMarketOperatorDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(TRANSFER_MARKET_OPERATOR_DISCRIMINATOR)
}

export type TransferMarketOperatorInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountMaster extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? WritableAccount<TAccountMarket> : TAccountMarket,
			TAccountMasterAccount extends string
				? ReadonlyAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountMaster extends string
				? WritableSignerAccount<TAccountMaster> & AccountSignerMeta<TAccountMaster>
				: TAccountMaster,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type TransferMarketOperatorInstructionData = {
	discriminator: ReadonlyUint8Array
	id: ReadonlyUint8Array
	newOperator: Address
}

export type TransferMarketOperatorInstructionDataArgs = {
	id: ReadonlyUint8Array
	newOperator: Address
}

export function getTransferMarketOperatorInstructionDataEncoder(): FixedSizeEncoder<TransferMarketOperatorInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["id", fixEncoderSize(getBytesEncoder(), 32)],
			["newOperator", getAddressEncoder()]
		]),
		value => ({
			...value,
			discriminator: TRANSFER_MARKET_OPERATOR_DISCRIMINATOR
		})
	)
}

export function getTransferMarketOperatorInstructionDataDecoder(): FixedSizeDecoder<TransferMarketOperatorInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["id", fixDecoderSize(getBytesDecoder(), 32)],
		["newOperator", getAddressDecoder()]
	])
}

export function getTransferMarketOperatorInstructionDataCodec(): FixedSizeCodec<
	TransferMarketOperatorInstructionDataArgs,
	TransferMarketOperatorInstructionData
> {
	return combineCodec(
		getTransferMarketOperatorInstructionDataEncoder(),
		getTransferMarketOperatorInstructionDataDecoder()
	)
}

export type TransferMarketOperatorAsyncInput<
	TAccountMarket extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market?: Address<TAccountMarket>
	masterAccount?: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	id: TransferMarketOperatorInstructionDataArgs["id"]
	newOperator: TransferMarketOperatorInstructionDataArgs["newOperator"]
}

export async function getTransferMarketOperatorInstructionAsync<
	TAccountMarket extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: TransferMarketOperatorAsyncInput<
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	TransferMarketOperatorInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.market.value) {
		accounts.market.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 114, 107,
						101, 116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id))
			]
		})
	}
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getTransferMarketOperatorInstructionDataEncoder().encode(
			args as TransferMarketOperatorInstructionDataArgs
		),
		programAddress
	} as TransferMarketOperatorInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type TransferMarketOperatorInput<
	TAccountMarket extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market: Address<TAccountMarket>
	masterAccount: Address<TAccountMasterAccount>
	master: TransactionSigner<TAccountMaster>
	systemProgram?: Address<TAccountSystemProgram>
	id: TransferMarketOperatorInstructionDataArgs["id"]
	newOperator: TransferMarketOperatorInstructionDataArgs["newOperator"]
}

export function getTransferMarketOperatorInstruction<
	TAccountMarket extends string,
	TAccountMasterAccount extends string,
	TAccountMaster extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: TransferMarketOperatorInput<
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): TransferMarketOperatorInstruction<
	TProgramAddress,
	TAccountMarket,
	TAccountMasterAccount,
	TAccountMaster,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		master: { value: input.master ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.systemProgram)
		],
		data: getTransferMarketOperatorInstructionDataEncoder().encode(
			args as TransferMarketOperatorInstructionDataArgs
		),
		programAddress
	} as TransferMarketOperatorInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountMasterAccount,
		TAccountMaster,
		TAccountSystemProgram
	>)
}

export type ParsedTransferMarketOperatorInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		market: TAccountMetas[0]
		masterAccount: TAccountMetas[1]
		master: TAccountMetas[2]
		systemProgram: TAccountMetas[3]
	}
	data: TransferMarketOperatorInstructionData
}

export function parseTransferMarketOperatorInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedTransferMarketOperatorInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 4) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			masterAccount: getNextAccount(),
			master: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getTransferMarketOperatorInstructionDataDecoder().decode(instruction.data)
	}
}
