/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressDecoder,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getF64Decoder,
	getF64Encoder,
	getI32Decoder,
	getI32Encoder,
	getOptionDecoder,
	getOptionEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	getU16Decoder,
	getU16Encoder,
	getU32Decoder,
	getU32Encoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type Option,
	type OptionOrNullable,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectSome, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const UPDATE_MARKET_CONFIG_DISCRIMINATOR = new Uint8Array([
	91, 87, 149, 101, 110, 116, 16, 120
])

export function getUpdateMarketConfigDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(UPDATE_MARKET_CONFIG_DISCRIMINATOR)
}

export type UpdateMarketConfigInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMarket extends string | AccountMeta<string> = string,
	TAccountOperator extends string | AccountMeta<string> = string,
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountMarket extends string ? WritableAccount<TAccountMarket> : TAccountMarket,
			TAccountOperator extends string
				? WritableSignerAccount<TAccountOperator> & AccountSignerMeta<TAccountOperator>
				: TAccountOperator,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type UpdateMarketConfigInstructionData = {
	discriminator: ReadonlyUint8Array
	id: ReadonlyUint8Array
	minSettleDelayEpochsSecs: Option<number>
	maxSettleDelayEpochsSecs: Option<number>
	feeBps: Option<number>
	minStake: Option<bigint>
	maxStake: Option<bigint>
	minPremiumBps: Option<number>
	callLambda: Option<number>
	putLambda: Option<number>
	vegaBuffer: Option<number>
	stalenessMaxSec: Option<number>
	priceExponent: Option<number>
	halfLifeSecs: Option<bigint>
	backAuthority: Option<Address>
}

export type UpdateMarketConfigInstructionDataArgs = {
	id: ReadonlyUint8Array
	minSettleDelayEpochsSecs: OptionOrNullable<number>
	maxSettleDelayEpochsSecs: OptionOrNullable<number>
	feeBps: OptionOrNullable<number>
	minStake: OptionOrNullable<number | bigint>
	maxStake: OptionOrNullable<number | bigint>
	minPremiumBps: OptionOrNullable<number>
	callLambda: OptionOrNullable<number>
	putLambda: OptionOrNullable<number>
	vegaBuffer: OptionOrNullable<number>
	stalenessMaxSec: OptionOrNullable<number>
	priceExponent: OptionOrNullable<number>
	halfLifeSecs: OptionOrNullable<number | bigint>
	backAuthority: OptionOrNullable<Address>
}

export function getUpdateMarketConfigInstructionDataEncoder(): Encoder<UpdateMarketConfigInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["id", fixEncoderSize(getBytesEncoder(), 32)],
			["minSettleDelayEpochsSecs", getOptionEncoder(getU32Encoder())],
			["maxSettleDelayEpochsSecs", getOptionEncoder(getU32Encoder())],
			["feeBps", getOptionEncoder(getU16Encoder())],
			["minStake", getOptionEncoder(getU64Encoder())],
			["maxStake", getOptionEncoder(getU64Encoder())],
			["minPremiumBps", getOptionEncoder(getU16Encoder())],
			["callLambda", getOptionEncoder(getF64Encoder())],
			["putLambda", getOptionEncoder(getF64Encoder())],
			["vegaBuffer", getOptionEncoder(getF64Encoder())],
			["stalenessMaxSec", getOptionEncoder(getU32Encoder())],
			["priceExponent", getOptionEncoder(getI32Encoder())],
			["halfLifeSecs", getOptionEncoder(getU64Encoder())],
			["backAuthority", getOptionEncoder(getAddressEncoder())]
		]),
		value => ({
			...value,
			discriminator: UPDATE_MARKET_CONFIG_DISCRIMINATOR
		})
	)
}

export function getUpdateMarketConfigInstructionDataDecoder(): Decoder<UpdateMarketConfigInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["id", fixDecoderSize(getBytesDecoder(), 32)],
		["minSettleDelayEpochsSecs", getOptionDecoder(getU32Decoder())],
		["maxSettleDelayEpochsSecs", getOptionDecoder(getU32Decoder())],
		["feeBps", getOptionDecoder(getU16Decoder())],
		["minStake", getOptionDecoder(getU64Decoder())],
		["maxStake", getOptionDecoder(getU64Decoder())],
		["minPremiumBps", getOptionDecoder(getU16Decoder())],
		["callLambda", getOptionDecoder(getF64Decoder())],
		["putLambda", getOptionDecoder(getF64Decoder())],
		["vegaBuffer", getOptionDecoder(getF64Decoder())],
		["stalenessMaxSec", getOptionDecoder(getU32Decoder())],
		["priceExponent", getOptionDecoder(getI32Decoder())],
		["halfLifeSecs", getOptionDecoder(getU64Decoder())],
		["backAuthority", getOptionDecoder(getAddressDecoder())]
	])
}

export function getUpdateMarketConfigInstructionDataCodec(): Codec<
	UpdateMarketConfigInstructionDataArgs,
	UpdateMarketConfigInstructionData
> {
	return combineCodec(
		getUpdateMarketConfigInstructionDataEncoder(),
		getUpdateMarketConfigInstructionDataDecoder()
	)
}

export type UpdateMarketConfigAsyncInput<
	TAccountMarket extends string = string,
	TAccountOperator extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market?: Address<TAccountMarket>
	operator: TransactionSigner<TAccountOperator>
	systemProgram?: Address<TAccountSystemProgram>
	id: UpdateMarketConfigInstructionDataArgs["id"]
	minSettleDelayEpochsSecs: UpdateMarketConfigInstructionDataArgs["minSettleDelayEpochsSecs"]
	maxSettleDelayEpochsSecs: UpdateMarketConfigInstructionDataArgs["maxSettleDelayEpochsSecs"]
	feeBps: UpdateMarketConfigInstructionDataArgs["feeBps"]
	minStake: UpdateMarketConfigInstructionDataArgs["minStake"]
	maxStake: UpdateMarketConfigInstructionDataArgs["maxStake"]
	minPremiumBps: UpdateMarketConfigInstructionDataArgs["minPremiumBps"]
	callLambda: UpdateMarketConfigInstructionDataArgs["callLambda"]
	putLambda: UpdateMarketConfigInstructionDataArgs["putLambda"]
	vegaBuffer: UpdateMarketConfigInstructionDataArgs["vegaBuffer"]
	stalenessMaxSec: UpdateMarketConfigInstructionDataArgs["stalenessMaxSec"]
	priceExponent: UpdateMarketConfigInstructionDataArgs["priceExponent"]
	halfLifeSecs: UpdateMarketConfigInstructionDataArgs["halfLifeSecs"]
	backAuthority: UpdateMarketConfigInstructionDataArgs["backAuthority"]
}

export async function getUpdateMarketConfigInstructionAsync<
	TAccountMarket extends string,
	TAccountOperator extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: UpdateMarketConfigAsyncInput<TAccountMarket, TAccountOperator, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	UpdateMarketConfigInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountOperator,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		operator: { value: input.operator ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.market.value) {
		accounts.market.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 114, 107,
						101, 116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				fixEncoderSize(getBytesEncoder(), 32).encode(expectSome(args.id))
			]
		})
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.systemProgram)
		],
		data: getUpdateMarketConfigInstructionDataEncoder().encode(
			args as UpdateMarketConfigInstructionDataArgs
		),
		programAddress
	} as UpdateMarketConfigInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountOperator,
		TAccountSystemProgram
	>)
}

export type UpdateMarketConfigInput<
	TAccountMarket extends string = string,
	TAccountOperator extends string = string,
	TAccountSystemProgram extends string = string
> = {
	market: Address<TAccountMarket>
	operator: TransactionSigner<TAccountOperator>
	systemProgram?: Address<TAccountSystemProgram>
	id: UpdateMarketConfigInstructionDataArgs["id"]
	minSettleDelayEpochsSecs: UpdateMarketConfigInstructionDataArgs["minSettleDelayEpochsSecs"]
	maxSettleDelayEpochsSecs: UpdateMarketConfigInstructionDataArgs["maxSettleDelayEpochsSecs"]
	feeBps: UpdateMarketConfigInstructionDataArgs["feeBps"]
	minStake: UpdateMarketConfigInstructionDataArgs["minStake"]
	maxStake: UpdateMarketConfigInstructionDataArgs["maxStake"]
	minPremiumBps: UpdateMarketConfigInstructionDataArgs["minPremiumBps"]
	callLambda: UpdateMarketConfigInstructionDataArgs["callLambda"]
	putLambda: UpdateMarketConfigInstructionDataArgs["putLambda"]
	vegaBuffer: UpdateMarketConfigInstructionDataArgs["vegaBuffer"]
	stalenessMaxSec: UpdateMarketConfigInstructionDataArgs["stalenessMaxSec"]
	priceExponent: UpdateMarketConfigInstructionDataArgs["priceExponent"]
	halfLifeSecs: UpdateMarketConfigInstructionDataArgs["halfLifeSecs"]
	backAuthority: UpdateMarketConfigInstructionDataArgs["backAuthority"]
}

export function getUpdateMarketConfigInstruction<
	TAccountMarket extends string,
	TAccountOperator extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: UpdateMarketConfigInput<TAccountMarket, TAccountOperator, TAccountSystemProgram>,
	config?: { programAddress?: TProgramAddress }
): UpdateMarketConfigInstruction<
	TProgramAddress,
	TAccountMarket,
	TAccountOperator,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		market: { value: input.market ?? null, isWritable: true },
		operator: { value: input.operator ?? null, isWritable: true },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.market),
			getAccountMeta(accounts.operator),
			getAccountMeta(accounts.systemProgram)
		],
		data: getUpdateMarketConfigInstructionDataEncoder().encode(
			args as UpdateMarketConfigInstructionDataArgs
		),
		programAddress
	} as UpdateMarketConfigInstruction<
		TProgramAddress,
		TAccountMarket,
		TAccountOperator,
		TAccountSystemProgram
	>)
}

export type ParsedUpdateMarketConfigInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		market: TAccountMetas[0]
		operator: TAccountMetas[1]
		systemProgram: TAccountMetas[2]
	}
	data: UpdateMarketConfigInstructionData
}

export function parseUpdateMarketConfigInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateMarketConfigInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 3) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			market: getNextAccount(),
			operator: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getUpdateMarketConfigInstructionDataDecoder().decode(instruction.data)
	}
}
