/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type AccountMeta,
	type AccountSignerMeta,
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getAddressEncoder,
	getBytesDecoder,
	getBytesEncoder,
	getProgramDerivedAddress,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder,
	type Instruction,
	type InstructionWithAccounts,
	type InstructionWithData,
	type ReadonlyAccount,
	type ReadonlyUint8Array,
	type TransactionSigner,
	transformEncoder,
	type WritableAccount,
	type WritableSignerAccount
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"
import { expectAddress, getAccountMetaFactory, type ResolvedAccount } from "../shared"

export const WITHDRAW_VAULT_DISCRIMINATOR = new Uint8Array([135, 7, 237, 120, 149, 94, 95, 7])

export function getWithdrawVaultDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(WITHDRAW_VAULT_DISCRIMINATOR)
}

export type WithdrawVaultInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountVault extends string | AccountMeta<string> = string,
	TAccountVaultTokenAccount extends string | AccountMeta<string> = string,
	TAccountMasterAccount extends string | AccountMeta<string> = string,
	TAccountUserTokenAccount extends string | AccountMeta<string> = string,
	TAccountMaster extends string | AccountMeta<string> = string,
	TAccountMint extends string | AccountMeta<string> = string,
	TAccountAssociatedTokenProgram extends
		| string
		| AccountMeta<string> = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
	TAccountTokenProgram extends
		| string
		| AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	TAccountSystemProgram extends string | AccountMeta<string> = "11111111111111111111111111111111",
	TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
	InstructionWithData<ReadonlyUint8Array> &
	InstructionWithAccounts<
		[
			TAccountVault extends string ? WritableAccount<TAccountVault> : TAccountVault,
			TAccountVaultTokenAccount extends string
				? WritableAccount<TAccountVaultTokenAccount>
				: TAccountVaultTokenAccount,
			TAccountMasterAccount extends string
				? ReadonlyAccount<TAccountMasterAccount>
				: TAccountMasterAccount,
			TAccountUserTokenAccount extends string
				? WritableAccount<TAccountUserTokenAccount>
				: TAccountUserTokenAccount,
			TAccountMaster extends string
				? WritableSignerAccount<TAccountMaster> & AccountSignerMeta<TAccountMaster>
				: TAccountMaster,
			TAccountMint extends string ? ReadonlyAccount<TAccountMint> : TAccountMint,
			TAccountAssociatedTokenProgram extends string
				? ReadonlyAccount<TAccountAssociatedTokenProgram>
				: TAccountAssociatedTokenProgram,
			TAccountTokenProgram extends string
				? ReadonlyAccount<TAccountTokenProgram>
				: TAccountTokenProgram,
			TAccountSystemProgram extends string
				? ReadonlyAccount<TAccountSystemProgram>
				: TAccountSystemProgram,
			...TRemainingAccounts
		]
	>

export type WithdrawVaultInstructionData = {
	discriminator: ReadonlyUint8Array
	amount: bigint
}

export type WithdrawVaultInstructionDataArgs = { amount: number | bigint }

export function getWithdrawVaultInstructionDataEncoder(): FixedSizeEncoder<WithdrawVaultInstructionDataArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["amount", getU64Encoder()]
		]),
		value => ({ ...value, discriminator: WITHDRAW_VAULT_DISCRIMINATOR })
	)
}

export function getWithdrawVaultInstructionDataDecoder(): FixedSizeDecoder<WithdrawVaultInstructionData> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["amount", getU64Decoder()]
	])
}

export function getWithdrawVaultInstructionDataCodec(): FixedSizeCodec<
	WithdrawVaultInstructionDataArgs,
	WithdrawVaultInstructionData
> {
	return combineCodec(
		getWithdrawVaultInstructionDataEncoder(),
		getWithdrawVaultInstructionDataDecoder()
	)
}

export type WithdrawVaultAsyncInput<
	TAccountVault extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountMint extends string = string,
	TAccountAssociatedTokenProgram extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	vault?: Address<TAccountVault>
	vaultTokenAccount?: Address<TAccountVaultTokenAccount>
	masterAccount?: Address<TAccountMasterAccount>
	userTokenAccount?: Address<TAccountUserTokenAccount>
	master: TransactionSigner<TAccountMaster>
	mint: Address<TAccountMint>
	associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	amount: WithdrawVaultInstructionDataArgs["amount"]
}

export async function getWithdrawVaultInstructionAsync<
	TAccountVault extends string,
	TAccountVaultTokenAccount extends string,
	TAccountMasterAccount extends string,
	TAccountUserTokenAccount extends string,
	TAccountMaster extends string,
	TAccountMint extends string,
	TAccountAssociatedTokenProgram extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: WithdrawVaultAsyncInput<
		TAccountVault,
		TAccountVaultTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): Promise<
	WithdrawVaultInstruction<
		TProgramAddress,
		TAccountVault,
		TAccountVaultTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		vault: { value: input.vault ?? null, isWritable: true },
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		master: { value: input.master ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		associatedTokenProgram: {
			value: input.associatedTokenProgram ?? null,
			isWritable: false
		},
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.vault.value) {
		accounts.vault.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.vaultTokenAccount.value) {
		accounts.vaultTokenAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 118, 97, 117, 108,
						116, 95, 97, 99, 99, 111, 117, 110, 116
					])
				),
				getAddressEncoder().encode(expectAddress(accounts.vault.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.masterAccount.value) {
		accounts.masterAccount.value = await getProgramDerivedAddress({
			programAddress,
			seeds: [
				getBytesEncoder().encode(
					new Uint8Array([
						98, 105, 110, 97, 114, 121, 95, 111, 112, 116, 105, 111, 110, 95, 109, 97, 115, 116,
						101, 114, 95, 97, 99, 99, 111, 117, 110, 116
					])
				)
			]
		})
	}
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.userTokenAccount.value) {
		accounts.userTokenAccount.value = await getProgramDerivedAddress({
			programAddress:
				"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
			seeds: [
				getAddressEncoder().encode(expectAddress(accounts.master.value)),
				getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
				getAddressEncoder().encode(expectAddress(accounts.mint.value))
			]
		})
	}
	if (!accounts.associatedTokenProgram.value) {
		accounts.associatedTokenProgram.value =
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.associatedTokenProgram),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getWithdrawVaultInstructionDataEncoder().encode(args as WithdrawVaultInstructionDataArgs),
		programAddress
	} as WithdrawVaultInstruction<
		TProgramAddress,
		TAccountVault,
		TAccountVaultTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type WithdrawVaultInput<
	TAccountVault extends string = string,
	TAccountVaultTokenAccount extends string = string,
	TAccountMasterAccount extends string = string,
	TAccountUserTokenAccount extends string = string,
	TAccountMaster extends string = string,
	TAccountMint extends string = string,
	TAccountAssociatedTokenProgram extends string = string,
	TAccountTokenProgram extends string = string,
	TAccountSystemProgram extends string = string
> = {
	vault: Address<TAccountVault>
	vaultTokenAccount: Address<TAccountVaultTokenAccount>
	masterAccount: Address<TAccountMasterAccount>
	userTokenAccount: Address<TAccountUserTokenAccount>
	master: TransactionSigner<TAccountMaster>
	mint: Address<TAccountMint>
	associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
	tokenProgram?: Address<TAccountTokenProgram>
	systemProgram?: Address<TAccountSystemProgram>
	amount: WithdrawVaultInstructionDataArgs["amount"]
}

export function getWithdrawVaultInstruction<
	TAccountVault extends string,
	TAccountVaultTokenAccount extends string,
	TAccountMasterAccount extends string,
	TAccountUserTokenAccount extends string,
	TAccountMaster extends string,
	TAccountMint extends string,
	TAccountAssociatedTokenProgram extends string,
	TAccountTokenProgram extends string,
	TAccountSystemProgram extends string,
	TProgramAddress extends Address = typeof BO_SC_PROGRAM_ADDRESS
>(
	input: WithdrawVaultInput<
		TAccountVault,
		TAccountVaultTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>,
	config?: { programAddress?: TProgramAddress }
): WithdrawVaultInstruction<
	TProgramAddress,
	TAccountVault,
	TAccountVaultTokenAccount,
	TAccountMasterAccount,
	TAccountUserTokenAccount,
	TAccountMaster,
	TAccountMint,
	TAccountAssociatedTokenProgram,
	TAccountTokenProgram,
	TAccountSystemProgram
> {
	// Program address.
	const programAddress = config?.programAddress ?? BO_SC_PROGRAM_ADDRESS

	// Original accounts.
	const originalAccounts = {
		vault: { value: input.vault ?? null, isWritable: true },
		vaultTokenAccount: {
			value: input.vaultTokenAccount ?? null,
			isWritable: true
		},
		masterAccount: { value: input.masterAccount ?? null, isWritable: false },
		userTokenAccount: {
			value: input.userTokenAccount ?? null,
			isWritable: true
		},
		master: { value: input.master ?? null, isWritable: true },
		mint: { value: input.mint ?? null, isWritable: false },
		associatedTokenProgram: {
			value: input.associatedTokenProgram ?? null,
			isWritable: false
		},
		tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
		systemProgram: { value: input.systemProgram ?? null, isWritable: false }
	}
	const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

	// Original args.
	const args = { ...input }

	// Resolve default values.
	if (!accounts.tokenProgram.value) {
		accounts.tokenProgram.value =
			"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">
	}
	if (!accounts.associatedTokenProgram.value) {
		accounts.associatedTokenProgram.value =
			"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">
	}
	if (!accounts.systemProgram.value) {
		accounts.systemProgram.value =
			"11111111111111111111111111111111" as Address<"11111111111111111111111111111111">
	}

	const getAccountMeta = getAccountMetaFactory(programAddress, "programId")
	return Object.freeze({
		accounts: [
			getAccountMeta(accounts.vault),
			getAccountMeta(accounts.vaultTokenAccount),
			getAccountMeta(accounts.masterAccount),
			getAccountMeta(accounts.userTokenAccount),
			getAccountMeta(accounts.master),
			getAccountMeta(accounts.mint),
			getAccountMeta(accounts.associatedTokenProgram),
			getAccountMeta(accounts.tokenProgram),
			getAccountMeta(accounts.systemProgram)
		],
		data: getWithdrawVaultInstructionDataEncoder().encode(args as WithdrawVaultInstructionDataArgs),
		programAddress
	} as WithdrawVaultInstruction<
		TProgramAddress,
		TAccountVault,
		TAccountVaultTokenAccount,
		TAccountMasterAccount,
		TAccountUserTokenAccount,
		TAccountMaster,
		TAccountMint,
		TAccountAssociatedTokenProgram,
		TAccountTokenProgram,
		TAccountSystemProgram
	>)
}

export type ParsedWithdrawVaultInstruction<
	TProgram extends string = typeof BO_SC_PROGRAM_ADDRESS,
	TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
	programAddress: Address<TProgram>
	accounts: {
		vault: TAccountMetas[0]
		vaultTokenAccount: TAccountMetas[1]
		masterAccount: TAccountMetas[2]
		userTokenAccount: TAccountMetas[3]
		master: TAccountMetas[4]
		mint: TAccountMetas[5]
		associatedTokenProgram: TAccountMetas[6]
		tokenProgram: TAccountMetas[7]
		systemProgram: TAccountMetas[8]
	}
	data: WithdrawVaultInstructionData
}

export function parseWithdrawVaultInstruction<
	TProgram extends string,
	TAccountMetas extends readonly AccountMeta[]
>(
	instruction: Instruction<TProgram> &
		InstructionWithAccounts<TAccountMetas> &
		InstructionWithData<ReadonlyUint8Array>
): ParsedWithdrawVaultInstruction<TProgram, TAccountMetas> {
	if (instruction.accounts.length < 9) {
		// TODO: Coded error.
		throw new Error("Not enough accounts")
	}
	let accountIndex = 0
	const getNextAccount = () => {
		const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
		accountIndex += 1
		return accountMeta
	}
	return {
		programAddress: instruction.programAddress,
		accounts: {
			vault: getNextAccount(),
			vaultTokenAccount: getNextAccount(),
			masterAccount: getNextAccount(),
			userTokenAccount: getNextAccount(),
			master: getNextAccount(),
			mint: getNextAccount(),
			associatedTokenProgram: getNextAccount(),
			tokenProgram: getNextAccount(),
			systemProgram: getNextAccount()
		},
		data: getWithdrawVaultInstructionDataDecoder().decode(instruction.data)
	}
}
