/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Account,
	type Address,
	assertAccountExists,
	assertAccountsExist,
	combineCodec,
	decodeAccount,
	type EncodedAccount,
	type FetchAccountConfig,
	type FetchAccountsConfig,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fetchEncodedAccount,
	fetchEncodedAccounts,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getStructDecoder,
	getStructEncoder,
	getU8Decoder,
	getU8Encoder,
	getU64Decoder,
	getU64Encoder,
	type MaybeAccount,
	type MaybeEncodedAccount,
	type ReadonlyUint8Array,
	transformEncoder
} from "@solana/kit"

export const POOL_ACCOUNT_DISCRIMINATOR = new Uint8Array([116, 210, 187, 119, 196, 196, 52, 137])

export function getPoolAccountDiscriminatorBytes() {
	return fixEncoderSize(getBytesEncoder(), 8).encode(POOL_ACCOUNT_DISCRIMINATOR)
}

export type PoolAccount = {
	discriminator: ReadonlyUint8Array
	bump: number
	total: bigint
	transferred: bigint
	locked: bigint
}

export type PoolAccountArgs = {
	bump: number
	total: number | bigint
	transferred: number | bigint
	locked: number | bigint
}

/** Gets the encoder for {@link PoolAccountArgs} account data. */
export function getPoolAccountEncoder(): FixedSizeEncoder<PoolAccountArgs> {
	return transformEncoder(
		getStructEncoder([
			["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
			["bump", getU8Encoder()],
			["total", getU64Encoder()],
			["transferred", getU64Encoder()],
			["locked", getU64Encoder()]
		]),
		value => ({ ...value, discriminator: POOL_ACCOUNT_DISCRIMINATOR })
	)
}

/** Gets the decoder for {@link PoolAccount} account data. */
export function getPoolAccountDecoder(): FixedSizeDecoder<PoolAccount> {
	return getStructDecoder([
		["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
		["bump", getU8Decoder()],
		["total", getU64Decoder()],
		["transferred", getU64Decoder()],
		["locked", getU64Decoder()]
	])
}

/** Gets the codec for {@link PoolAccount} account data. */
export function getPoolAccountCodec(): FixedSizeCodec<PoolAccountArgs, PoolAccount> {
	return combineCodec(getPoolAccountEncoder(), getPoolAccountDecoder())
}

export function decodePoolAccount<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress>
): Account<PoolAccount, TAddress>
export function decodePoolAccount<TAddress extends string = string>(
	encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<PoolAccount, TAddress>
export function decodePoolAccount<TAddress extends string = string>(
	encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<PoolAccount, TAddress> | MaybeAccount<PoolAccount, TAddress> {
	return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getPoolAccountDecoder())
}

export async function fetchPoolAccount<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<Account<PoolAccount, TAddress>> {
	const maybeAccount = await fetchMaybePoolAccount(rpc, address, config)
	assertAccountExists(maybeAccount)
	return maybeAccount
}

export async function fetchMaybePoolAccount<TAddress extends string = string>(
	rpc: Parameters<typeof fetchEncodedAccount>[0],
	address: Address<TAddress>,
	config?: FetchAccountConfig
): Promise<MaybeAccount<PoolAccount, TAddress>> {
	const maybeAccount = await fetchEncodedAccount(rpc, address, config)
	return decodePoolAccount(maybeAccount)
}

export async function fetchAllPoolAccount(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<Account<PoolAccount>[]> {
	const maybeAccounts = await fetchAllMaybePoolAccount(rpc, addresses, config)
	assertAccountsExist(maybeAccounts)
	return maybeAccounts
}

export async function fetchAllMaybePoolAccount(
	rpc: Parameters<typeof fetchEncodedAccounts>[0],
	addresses: Array<Address>,
	config?: FetchAccountsConfig
): Promise<MaybeAccount<PoolAccount>[]> {
	const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config)
	return maybeAccounts.map(maybeAccount => decodePoolAccount(maybeAccount))
}

export function getPoolAccountSize(): number {
	return 33
}
