/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	isProgramError,
	type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
	type SolanaError
} from "@solana/kit"
import { BO_SC_PROGRAM_ADDRESS } from "../programs"

/** Unauthorized: Unauthorized */
export const BO_SC_ERROR__UNAUTHORIZED = 0x1770 // 6000
/** Paused: Market is paused */
export const BO_SC_ERROR__PAUSED = 0x1771 // 6001
/** InvalidEpoch: Invalid epoch configuration */
export const BO_SC_ERROR__INVALID_EPOCH = 0x1772 // 6002
/** InvalidLambda: Invalid lambda */
export const BO_SC_ERROR__INVALID_LAMBDA = 0x1773 // 6003
/** InvalidBuffer: Invalid vega buffer */
export const BO_SC_ERROR__INVALID_BUFFER = 0x1774 // 6004
/** InvalidStakeBounds: Invalid stake bounds */
export const BO_SC_ERROR__INVALID_STAKE_BOUNDS = 0x1775 // 6005
/** StakeOutOfRange: Stake out of range */
export const BO_SC_ERROR__STAKE_OUT_OF_RANGE = 0x1776 // 6006
/** OracleStale: Oracle data is stale */
export const BO_SC_ERROR__ORACLE_STALE = 0x1777 // 6007
/** OracleReadFail: Oracle read failed */
export const BO_SC_ERROR__ORACLE_READ_FAIL = 0x1778 // 6008
/** ZeroPremium: Zero premium */
export const BO_SC_ERROR__ZERO_PREMIUM = 0x1779 // 6009
/** NotExpired: Position not yet expired */
export const BO_SC_ERROR__NOT_EXPIRED = 0x177a // 6010
/** AlreadySettled: Position already settled */
export const BO_SC_ERROR__ALREADY_SETTLED = 0x177b // 6011
/** MathOverflow: Math overflow */
export const BO_SC_ERROR__MATH_OVERFLOW = 0x177c // 6012
/** InvalidPrice: Invalid price */
export const BO_SC_ERROR__INVALID_PRICE = 0x177d // 6013
/** InvalidIV: Invalid IV */
export const BO_SC_ERROR__INVALID_I_V = 0x177e // 6014
/** InvalidSigma2: Invalid sigma2 */
export const BO_SC_ERROR__INVALID_SIGMA2 = 0x177f // 6015
/** InvalidFee: Invalid fee */
export const BO_SC_ERROR__INVALID_FEE = 0x1780 // 6016
/** InsufficientBalance: Insufficient balance */
export const BO_SC_ERROR__INSUFFICIENT_BALANCE = 0x1781 // 6017
/** InsufficientPoolLiquidity: Insufficient pool liquidity */
export const BO_SC_ERROR__INSUFFICIENT_POOL_LIQUIDITY = 0x1782 // 6018
/** InvalidMarket: Invalid market */
export const BO_SC_ERROR__INVALID_MARKET = 0x1783 // 6019
/** InvalidStaleness: Invalid s taleness */
export const BO_SC_ERROR__INVALID_STALENESS = 0x1784 // 6020
/** InvalidHalfLife: Invalid half life */
export const BO_SC_ERROR__INVALID_HALF_LIFE = 0x1785 // 6021
/** InvalidUser: Invalid user */
export const BO_SC_ERROR__INVALID_USER = 0x1786 // 6022
/** InvalidAmount: Invalid amount */
export const BO_SC_ERROR__INVALID_AMOUNT = 0x1787 // 6023
/** OracleLowConfidence: Oracle confidence too low */
export const BO_SC_ERROR__ORACLE_LOW_CONFIDENCE = 0x1788 // 6024
/** InvalidTokenMint: Invalid token mint. Only USDC is accepted. */
export const BO_SC_ERROR__INVALID_TOKEN_MINT = 0x1789 // 6025
/** InvalidSettleUser: Invalid user. User's pubkey mismatch. */
export const BO_SC_ERROR__INVALID_SETTLE_USER = 0x178a // 6026
/** MarketPaused: Market paused */
export const BO_SC_ERROR__MARKET_PAUSED = 0x178b // 6027
/** InvalidFeeProvider: Invalid fee provider. Fee Provider's pubkey mismatch. */
export const BO_SC_ERROR__INVALID_FEE_PROVIDER = 0x178c // 6028
/** InvalidSettleDelayEpochsSecs: Invalid settle delay epochs secs. */
export const BO_SC_ERROR__INVALID_SETTLE_DELAY_EPOCHS_SECS = 0x178d // 6029
/** InvalidStrike: Invalid strike price percentage */
export const BO_SC_ERROR__INVALID_STRIKE = 0x178e // 6030
/** InvalidPriceTimestamp: Invalid price timestamp */
export const BO_SC_ERROR__INVALID_PRICE_TIMESTAMP = 0x178f // 6031
/** InvalidAccountCount: Invalid account count in remaining_accounts */
export const BO_SC_ERROR__INVALID_ACCOUNT_COUNT = 0x1790 // 6032
/** InvalidPositionAccount: Invalid position account */
export const BO_SC_ERROR__INVALID_POSITION_ACCOUNT = 0x1791 // 6033
/** InvalidUserTokenAccount: Invalid user token account. Must be the user's ATA for the token mint. */
export const BO_SC_ERROR__INVALID_USER_TOKEN_ACCOUNT = 0x1792 // 6034
/** DuplicatePositionInBatch: Duplicate position in batch. Each position can only be settled once. */
export const BO_SC_ERROR__DUPLICATE_POSITION_IN_BATCH = 0x1793 // 6035
/** InsufficientUserFunds: Insufficient user funds to pay premium. */
export const BO_SC_ERROR__INSUFFICIENT_USER_FUNDS = 0x1794 // 6036
/** BatchSizeTooLarge: Batch size exceeds maximum allowed positions. */
export const BO_SC_ERROR__BATCH_SIZE_TOO_LARGE = 0x1795 // 6037

export type BoScError =
	| typeof BO_SC_ERROR__ALREADY_SETTLED
	| typeof BO_SC_ERROR__BATCH_SIZE_TOO_LARGE
	| typeof BO_SC_ERROR__DUPLICATE_POSITION_IN_BATCH
	| typeof BO_SC_ERROR__INSUFFICIENT_BALANCE
	| typeof BO_SC_ERROR__INSUFFICIENT_POOL_LIQUIDITY
	| typeof BO_SC_ERROR__INSUFFICIENT_USER_FUNDS
	| typeof BO_SC_ERROR__INVALID_ACCOUNT_COUNT
	| typeof BO_SC_ERROR__INVALID_AMOUNT
	| typeof BO_SC_ERROR__INVALID_BUFFER
	| typeof BO_SC_ERROR__INVALID_EPOCH
	| typeof BO_SC_ERROR__INVALID_FEE
	| typeof BO_SC_ERROR__INVALID_FEE_PROVIDER
	| typeof BO_SC_ERROR__INVALID_HALF_LIFE
	| typeof BO_SC_ERROR__INVALID_I_V
	| typeof BO_SC_ERROR__INVALID_LAMBDA
	| typeof BO_SC_ERROR__INVALID_MARKET
	| typeof BO_SC_ERROR__INVALID_POSITION_ACCOUNT
	| typeof BO_SC_ERROR__INVALID_PRICE
	| typeof BO_SC_ERROR__INVALID_PRICE_TIMESTAMP
	| typeof BO_SC_ERROR__INVALID_SETTLE_DELAY_EPOCHS_SECS
	| typeof BO_SC_ERROR__INVALID_SETTLE_USER
	| typeof BO_SC_ERROR__INVALID_SIGMA2
	| typeof BO_SC_ERROR__INVALID_STAKE_BOUNDS
	| typeof BO_SC_ERROR__INVALID_STALENESS
	| typeof BO_SC_ERROR__INVALID_STRIKE
	| typeof BO_SC_ERROR__INVALID_TOKEN_MINT
	| typeof BO_SC_ERROR__INVALID_USER
	| typeof BO_SC_ERROR__INVALID_USER_TOKEN_ACCOUNT
	| typeof BO_SC_ERROR__MARKET_PAUSED
	| typeof BO_SC_ERROR__MATH_OVERFLOW
	| typeof BO_SC_ERROR__NOT_EXPIRED
	| typeof BO_SC_ERROR__ORACLE_LOW_CONFIDENCE
	| typeof BO_SC_ERROR__ORACLE_READ_FAIL
	| typeof BO_SC_ERROR__ORACLE_STALE
	| typeof BO_SC_ERROR__PAUSED
	| typeof BO_SC_ERROR__STAKE_OUT_OF_RANGE
	| typeof BO_SC_ERROR__UNAUTHORIZED
	| typeof BO_SC_ERROR__ZERO_PREMIUM

let boScErrorMessages: Record<BoScError, string> | undefined
if (process.env.NODE_ENV !== "production") {
	boScErrorMessages = {
		[BO_SC_ERROR__ALREADY_SETTLED]: `Position already settled`,
		[BO_SC_ERROR__BATCH_SIZE_TOO_LARGE]: `Batch size exceeds maximum allowed positions.`,
		[BO_SC_ERROR__DUPLICATE_POSITION_IN_BATCH]: `Duplicate position in batch. Each position can only be settled once.`,
		[BO_SC_ERROR__INSUFFICIENT_BALANCE]: `Insufficient balance`,
		[BO_SC_ERROR__INSUFFICIENT_POOL_LIQUIDITY]: `Insufficient pool liquidity`,
		[BO_SC_ERROR__INSUFFICIENT_USER_FUNDS]: `Insufficient user funds to pay premium.`,
		[BO_SC_ERROR__INVALID_ACCOUNT_COUNT]: `Invalid account count in remaining_accounts`,
		[BO_SC_ERROR__INVALID_AMOUNT]: `Invalid amount`,
		[BO_SC_ERROR__INVALID_BUFFER]: `Invalid vega buffer`,
		[BO_SC_ERROR__INVALID_EPOCH]: `Invalid epoch configuration`,
		[BO_SC_ERROR__INVALID_FEE]: `Invalid fee`,
		[BO_SC_ERROR__INVALID_FEE_PROVIDER]: `Invalid fee provider. Fee Provider's pubkey mismatch.`,
		[BO_SC_ERROR__INVALID_HALF_LIFE]: `Invalid half life`,
		[BO_SC_ERROR__INVALID_I_V]: `Invalid IV`,
		[BO_SC_ERROR__INVALID_LAMBDA]: `Invalid lambda`,
		[BO_SC_ERROR__INVALID_MARKET]: `Invalid market`,
		[BO_SC_ERROR__INVALID_POSITION_ACCOUNT]: `Invalid position account`,
		[BO_SC_ERROR__INVALID_PRICE]: `Invalid price`,
		[BO_SC_ERROR__INVALID_PRICE_TIMESTAMP]: `Invalid price timestamp`,
		[BO_SC_ERROR__INVALID_SETTLE_DELAY_EPOCHS_SECS]: `Invalid settle delay epochs secs.`,
		[BO_SC_ERROR__INVALID_SETTLE_USER]: `Invalid user. User's pubkey mismatch.`,
		[BO_SC_ERROR__INVALID_SIGMA2]: `Invalid sigma2`,
		[BO_SC_ERROR__INVALID_STAKE_BOUNDS]: `Invalid stake bounds`,
		[BO_SC_ERROR__INVALID_STALENESS]: `Invalid s taleness`,
		[BO_SC_ERROR__INVALID_STRIKE]: `Invalid strike price percentage`,
		[BO_SC_ERROR__INVALID_TOKEN_MINT]: `Invalid token mint. Only USDC is accepted.`,
		[BO_SC_ERROR__INVALID_USER]: `Invalid user`,
		[BO_SC_ERROR__INVALID_USER_TOKEN_ACCOUNT]: `Invalid user token account. Must be the user's ATA for the token mint.`,
		[BO_SC_ERROR__MARKET_PAUSED]: `Market paused`,
		[BO_SC_ERROR__MATH_OVERFLOW]: `Math overflow`,
		[BO_SC_ERROR__NOT_EXPIRED]: `Position not yet expired`,
		[BO_SC_ERROR__ORACLE_LOW_CONFIDENCE]: `Oracle confidence too low`,
		[BO_SC_ERROR__ORACLE_READ_FAIL]: `Oracle read failed`,
		[BO_SC_ERROR__ORACLE_STALE]: `Oracle data is stale`,
		[BO_SC_ERROR__PAUSED]: `Market is paused`,
		[BO_SC_ERROR__STAKE_OUT_OF_RANGE]: `Stake out of range`,
		[BO_SC_ERROR__UNAUTHORIZED]: `Unauthorized`,
		[BO_SC_ERROR__ZERO_PREMIUM]: `Zero premium`
	}
}

export function getBoScErrorMessage(code: BoScError): string {
	if (process.env.NODE_ENV !== "production") {
		return (boScErrorMessages as Record<BoScError, string>)[code]
	}

	return "Error message not available in production bundles."
}

export function isBoScError<TProgramErrorCode extends BoScError>(
	error: unknown,
	transactionMessage: {
		instructions: Record<number, { programAddress: Address }>
	},
	code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
	Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
	return isProgramError<TProgramErrorCode>(error, transactionMessage, BO_SC_PROGRAM_ADDRESS, code)
}
