/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	fixDecoderSize,
	fixEncoderSize,
	getBytesDecoder,
	getBytesEncoder,
	getF64Decoder,
	getF64Encoder,
	getStructDecoder,
	getStructEncoder,
	type ReadonlyUint8Array
} from "@solana/kit"

export type InitializedMarket = {
	callLambda: number
	putLambda: number
	vegaBuffer: number
	impliedVolatility: number
	timeWindow: number
	feedId: ReadonlyUint8Array
}

export type InitializedMarketArgs = InitializedMarket

export function getInitializedMarketEncoder(): FixedSizeEncoder<InitializedMarketArgs> {
	return getStructEncoder([
		["callLambda", getF64Encoder()],
		["putLambda", getF64Encoder()],
		["vegaBuffer", getF64Encoder()],
		["impliedVolatility", getF64Encoder()],
		["timeWindow", getF64Encoder()],
		["feedId", fixEncoderSize(getBytesEncoder(), 32)]
	])
}

export function getInitializedMarketDecoder(): FixedSizeDecoder<InitializedMarket> {
	return getStructDecoder([
		["callLambda", getF64Decoder()],
		["putLambda", getF64Decoder()],
		["vegaBuffer", getF64Decoder()],
		["impliedVolatility", getF64Decoder()],
		["timeWindow", getF64Decoder()],
		["feedId", fixDecoderSize(getBytesDecoder(), 32)]
	])
}

export function getInitializedMarketCodec(): FixedSizeCodec<
	InitializedMarketArgs,
	InitializedMarket
> {
	return combineCodec(getInitializedMarketEncoder(), getInitializedMarketDecoder())
}
