/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	type Codec,
	combineCodec,
	type Decoder,
	type Encoder,
	getAddressDecoder,
	getAddressEncoder,
	getOptionDecoder,
	getOptionEncoder,
	getStructDecoder,
	getStructEncoder,
	type Option,
	type OptionOrNullable
} from "@solana/kit"

export type InitializedMaster = {
	master: Address
	pendingMaster: Option<Address>
}

export type InitializedMasterArgs = {
	master: Address
	pendingMaster: OptionOrNullable<Address>
}

export function getInitializedMasterEncoder(): Encoder<InitializedMasterArgs> {
	return getStructEncoder([
		["master", getAddressEncoder()],
		["pendingMaster", getOptionEncoder(getAddressEncoder())]
	])
}

export function getInitializedMasterDecoder(): Decoder<InitializedMaster> {
	return getStructDecoder([
		["master", getAddressDecoder()],
		["pendingMaster", getOptionDecoder(getAddressDecoder())]
	])
}

export function getInitializedMasterCodec(): Codec<InitializedMasterArgs, InitializedMaster> {
	return combineCodec(getInitializedMasterEncoder(), getInitializedMasterDecoder())
}
