/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getF64Decoder,
	getF64Encoder,
	getStructDecoder,
	getStructEncoder
} from "@solana/kit"

export type IVReset = { market: Address; newIv: number }

export type IVResetArgs = IVReset

export function getIVResetEncoder(): FixedSizeEncoder<IVResetArgs> {
	return getStructEncoder([
		["market", getAddressEncoder()],
		["newIv", getF64Encoder()]
	])
}

export function getIVResetDecoder(): FixedSizeDecoder<IVReset> {
	return getStructDecoder([
		["market", getAddressDecoder()],
		["newIv", getF64Decoder()]
	])
}

export function getIVResetCodec(): FixedSizeCodec<IVResetArgs, IVReset> {
	return combineCodec(getIVResetEncoder(), getIVResetDecoder())
}
