/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder,
	getU64Decoder,
	getU64Encoder
} from "@solana/kit"

export type PoolWithdrawn = {
	pool: Address
	amount: bigint
	destination: Address
}

export type PoolWithdrawnArgs = {
	pool: Address
	amount: number | bigint
	destination: Address
}

export function getPoolWithdrawnEncoder(): FixedSizeEncoder<PoolWithdrawnArgs> {
	return getStructEncoder([
		["pool", getAddressEncoder()],
		["amount", getU64Encoder()],
		["destination", getAddressEncoder()]
	])
}

export function getPoolWithdrawnDecoder(): FixedSizeDecoder<PoolWithdrawn> {
	return getStructDecoder([
		["pool", getAddressDecoder()],
		["amount", getU64Decoder()],
		["destination", getAddressDecoder()]
	])
}

export function getPoolWithdrawnCodec(): FixedSizeCodec<PoolWithdrawnArgs, PoolWithdrawn> {
	return combineCodec(getPoolWithdrawnEncoder(), getPoolWithdrawnDecoder())
}
