/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getEnumDecoder,
	getEnumEncoder
} from "@solana/kit"

export enum PositionMode {
	Single,
	Batch
}

export type PositionModeArgs = PositionMode

export function getPositionModeEncoder(): FixedSizeEncoder<PositionModeArgs> {
	return getEnumEncoder(PositionMode)
}

export function getPositionModeDecoder(): FixedSizeDecoder<PositionMode> {
	return getEnumDecoder(PositionMode)
}

export function getPositionModeCodec(): FixedSizeCodec<PositionModeArgs, PositionMode> {
	return combineCodec(getPositionModeEncoder(), getPositionModeDecoder())
}
