/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
	type Address,
	combineCodec,
	type FixedSizeCodec,
	type FixedSizeDecoder,
	type FixedSizeEncoder,
	getAddressDecoder,
	getAddressEncoder,
	getStructDecoder,
	getStructEncoder
} from "@solana/kit"

export type TransferredOperator = {
	market: Address
	oldOperator: Address
	operator: Address
}

export type TransferredOperatorArgs = TransferredOperator

export function getTransferredOperatorEncoder(): FixedSizeEncoder<TransferredOperatorArgs> {
	return getStructEncoder([
		["market", getAddressEncoder()],
		["oldOperator", getAddressEncoder()],
		["operator", getAddressEncoder()]
	])
}

export function getTransferredOperatorDecoder(): FixedSizeDecoder<TransferredOperator> {
	return getStructDecoder([
		["market", getAddressDecoder()],
		["oldOperator", getAddressDecoder()],
		["operator", getAddressDecoder()]
	])
}

export function getTransferredOperatorCodec(): FixedSizeCodec<
	TransferredOperatorArgs,
	TransferredOperator
> {
	return combineCodec(getTransferredOperatorEncoder(), getTransferredOperatorDecoder())
}
